// Precompiles templates/**/*.njk into src/generated/precompiled.ts, a plain
// ES module the Worker bundles at build time. This has to happen ahead of
// time because Workers bans eval()/new Function(), and every JS template
// engine -- nunjucks included -- compiles templates via new Function().
// nunjucks.precompile() runs that compiler here, in Node, and hands us the
// generated function *source*; only the resulting plain functions ship to
// the Worker, never a compile step.
//
// Run before `wrangler dev`/`wrangler deploy` picks up workers/site -- see
// the `predev`/`predeploy` scripts in workers/site/package.json.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import nunjucks from "nunjucks";
import { AutoescapeExtension } from "../src/autoescapeExtension";
import { BlocktransExtension } from "../src/blocktransExtension";
import { parsePoFile } from "../src/poParser";
import { LOCALES, type Locale } from "../src/i18n";

interface PrecompiledTemplate {
  name: string;
  template: string;
}

// nunjucks's default wrapper emits `window.nunjucksPrecompiled = ...`, a
// browser global that doesn't exist on Workers (globalThis does, window
// doesn't). This wrapper emits a plain ES module export instead, loaded at
// runtime via nunjucks's PrecompiledLoader (src/env.ts), which just does a
// plain object lookup -- no window dependency.
function esmWrapper(templates: PrecompiledTemplate[]): string {
  const varNames = templates.map((_t, i) => `t_${i}`);
  let out = "// AUTO-GENERATED by packages/templates/scripts/precompile.ts -- do not edit by hand.\n\n";
  templates.forEach((t, i) => {
    out += `const ${varNames[i]} = (function() {\n${t.template}\n})();\n`;
  });
  out += "\nexport const precompiledTemplates = {\n";
  templates.forEach((t, i) => {
    out += `  ${JSON.stringify(t.name)}: ${varNames[i]},\n`;
  });
  out += "};\n";
  return out;
}

const here = dirname(fileURLToPath(import.meta.url));
const templatesDir = join(here, "..", "templates");
const localeDir = join(here, "..", "locale");
const outDir = join(here, "..", "src", "generated");
const localesOutDir = join(outDir, "locales");
// Plain .js, not .ts: this is nunjucks's own code-generator output (untyped,
// not meant to be strict-mode-checked) -- .d.ts alongside it is what tsc
// actually reads on `import ... from "./generated/precompiled"`.
const outFile = join(outDir, "precompiled.js");
const outTypesFile = join(outDir, "precompiled.d.ts");

mkdirSync(outDir, { recursive: true });
mkdirSync(localesOutDir, { recursive: true });

// {% blocktrans %} needs the FULL nunjucks parser (nunjucks-slim strips
// nodes/parser to nothing -- see blocktransExtension.ts's module comment),
// registered on the Environment passed to precompile() so its .parse()
// method runs during compilation, same as every built-in tag.
const compileEnv = new nunjucks.Environment(null, { autoescape: true });
compileEnv.addExtension("blocktrans", new BlocktransExtension(nunjucks));
// {% autoescape %} -- same "needs the full parser at compile time" reasoning
// as blocktrans above; see autoescapeExtension.ts's module comment.
compileEnv.addExtension("autoescape", new AutoescapeExtension(nunjucks));

const source: string = nunjucks.precompile(templatesDir, {
  include: [/\.njk$/],
  wrapper: esmWrapper as unknown as (templates: PrecompiledTemplate[], opts: unknown) => string,
  env: compileEnv,
});

writeFileSync(outFile, source);
writeFileSync(
  outTypesFile,
  "// AUTO-GENERATED by packages/templates/scripts/precompile.ts -- do not edit by hand.\nexport declare const precompiledTemplates: Record<string, unknown>;\n",
);

const count = (source.match(/^const t_\d+ = /gm) ?? []).length;
console.log(`@givefood/templates: precompiled ${count} template(s) -> ${outFile}`);

// locale/{cy,ga,gd}/django.po -- copied verbatim from the Django app's own
// locale/ directory (§2.7.1) -- built into plain JSON catalogues, one per
// locale, dynamically imported at render time (i18n.ts).
for (const locale of LOCALES) {
  if (locale === "en") continue; // en is the source language, no catalogue
  const poPath = join(localeDir, locale, "django.po");
  const catalogue = parsePoFile(readFileSync(poPath, "utf-8"));
  writeFileSync(join(localesOutDir, `${locale}.json`), JSON.stringify(catalogue));
  console.log(`@givefood/templates: built ${Object.keys(catalogue).length} msgid(s) for locale "${locale satisfies Locale}"`);
}
