"""Compare primary-key sets between Postgres and D1, and delete from D1 what
Postgres no longer has.

    uv run --with psycopg2-binary python tools/pg-to-d1/reconcile.py            # report only
    uv run --with psycopg2-binary python tools/pg-to-d1/reconcile.py --apply    # delete the strays
    ... --tables foodbank,foodbankchange       # limit to named D1 tables
    ... --include-large                        # also check foodbankhit/place/postcode

WHY THIS EXISTS. extract_core.py loads with INSERT OR REPLACE and nothing
deletes, so a row removed in Postgres stays in D1 for ever. PLAN.md WP 7.4
names this reconciliation as a cutover requirement; it did not exist. The
gap is not hypothetical -- after a full ETL run on 2026-09-05,
foodbankdonationpoint held 5,744 rows and the run loaded 5,742, and
foodbankchange held 34,143 against 34,054 loaded. Those 91 rows are food
banks' donation points and needs that have been deleted in production and
are still being served by the port.

It reports BOTH directions, because they mean different things:

  in D1, not in Postgres   a deletion that never propagated. This is what
                           --apply removes.
  in Postgres, not in D1   a row the ETL never loaded -- a failed batch, a
                           WHERE clause in the table's own definition, or a
                           load that has not been run since the row was
                           created. NEVER deleted from anything; it is
                           reported so someone can decide, because the fix
                           is a load, not a delete.

--apply IS DESTRUCTIVE AND DEFAULTS OFF. It issues DELETE against the live
D1 database. Run it without the flag first and read the numbers: a
suspiciously large "in D1, not in Postgres" almost always means the table
list is wrong (a filtered table whose D1 copy is a superset by design), not
that production lost thousands of rows.

CHILD ROWS ARE NOT CASCADED. Deleting a foodbankchange here leaves its
foodbankchangeline rows behind; D1 has no foreign keys (PLAN.md §4.5) and
this script will not invent a cascade order. Reconcile the child tables in
the same run and their own strays are removed by their own PK diff --
which is why foodbankchangeline is in the default set.
"""

import os
import sys
import time
import urllib.error

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from extract_core import (  # noqa: E402
    DASHBOARD_TABLES,
    FOODCHARITY_ENV_PATH,
    GEO_TABLES,
    HOMEPAGE_TABLES,
    LAUNCH_GAP_TABLES,
    TABLES,
    TRANSLATION_TABLES,
    TokenBox,
    d1_query,
    load_env,
)

# Every (postgres table, d1 table) the ETL knows how to load, deduplicated --
# foodbankarticle appears in two of its lists. Taken from extract_core's own
# definitions rather than restated, so a table added there cannot be silently
# missed here.
# The 4th element of an entry, when present, carries the same `from_table` /
# `where` the loader uses. THEY MUST BE HONOURED HERE TOO. Without them the
# first version of this script reported foodbankchangetranslation as 73,790
# rows short, because Postgres holds translations in all 21 of Django's
# languages and the ETL deliberately loads only the three this port serves
# (PLAN.md §2.7.1). That is a filter, not a gap -- and a reconciliation that
# cries wolf on 74k rows is worse than none, because the real 91 get lost in
# it.
ALL_TABLES = []
for group in (TABLES, HOMEPAGE_TABLES, DASHBOARD_TABLES, TRANSLATION_TABLES, LAUNCH_GAP_TABLES, GEO_TABLES):
    for entry in group:
        kwargs = entry[3] if len(entry) > 3 else {}
        row = (entry[0], entry[1], kwargs.get("from_table"), kwargs.get("where"))
        if row not in ALL_TABLES:
            ALL_TABLES.append(row)

# ONLY THESE MAY BE --apply'd. Postgres is authoritative for them and the
# ids are shared, so a row in D1 and not in Postgres is a deletion that never
# propagated, full stop.
#
# EVERYTHING ELSE IS REPORT-ONLY, and the first run of this script is why.
# It found two tables where "stray in D1" means something entirely different:
#
#   foodbankarticle   40 stray, 37 missing. The port's OWN articles queue
#                     (workers/jobs/src/queues/articles.ts) inserts rows
#                     here, so D1 legitimately holds articles Postgres has
#                     never seen. Deleting them would delete the port's own
#                     work.
#   charityyear       4,180 stray against 4,179 missing -- essentially the
#                     whole table on both sides. replaceCharityYears()
#                     deletes and re-inserts, so the ids are generated by
#                     D1 and have never matched Postgres's. Reconciling this
#                     table by id is meaningless, not merely unsafe.
#
# The same will be true of any table the port writes to itself. Adding one
# here is a decision about who owns the data, so it is a list rather than a
# heuristic. Note the whole idea expires at cutover: afterwards D1 is
# authoritative and there is nothing to reconcile against.
DELETABLE = {
    "foodbank",
    "foodbanklocation",
    "foodbankdonationpoint",
    "foodbankchange",
    "foodbankchangeline",
    "foodbankchangetranslation",
    "parliamentaryconstituency",
    "orders",
    "orderline",
    "orderitem",
    "ordergroup",
    "foodbanksubscriber",
    "slugredirect",
    "place",
    "postcode",
}

# Excluded unless --include-large. Not because they cannot be checked -- they
# can, the paging below handles any size -- but because they are 3.7M rows
# between them and none of them is a thing anyone deletes: foodbankhit is
# append-only analytics, place and postcode are static reference data loaded
# once. Checking them costs ~750 D1 requests to prove nothing changed.
LARGE_TABLES = {"foodbankhit", "place", "postcode"}

# Rows per D1 SELECT when paging out an id column. Ints only, so the response
# stays small; the cap is D1's own result-size limit, not the row count.
D1_PAGE = 5000

# Ids per DELETE. D1 caps a statement at 100 bound parameters (see
# extract_core.py:63-75), and this binds one per id.
DELETE_BATCH = 90


def d1_ids(token_box, table):
    """Every id in a D1 table, paged. Ordered so the OFFSET is stable."""
    ids = set()
    offset = 0
    while True:
        resp = d1_query(token_box, f"SELECT id FROM {table} ORDER BY id LIMIT {D1_PAGE} OFFSET {offset}")
        rows = resp["result"][0]["results"]
        ids.update(r["id"] for r in rows)
        if len(rows) < D1_PAGE:
            return ids
        offset += D1_PAGE


def pg_ids(cur, table, from_table=None, where=None):
    """The id set the LOADER would produce -- same FROM and same WHERE, or
    the comparison is against rows the ETL was never asked to copy."""
    src = from_table or table
    # `from_table` aliases the base table (e.g. "... t JOIN ..."), so the id
    # column has to be qualified the way the loader's own select_cols are.
    alias = ""
    if from_table:
        parts = from_table.split()
        if len(parts) > 1 and parts[1].isalpha() and parts[1].upper() not in ("JOIN", "LEFT", "INNER"):
            alias = parts[1] + "."
    sql = f"SELECT {alias}id FROM {src}"
    if where:
        sql += f" WHERE {where}"
    cur.execute(sql)
    return {r[0] for r in cur.fetchall()}


def delete_from_d1(token_box, table, ids):
    deleted = 0
    ids = sorted(ids)
    for i in range(0, len(ids), DELETE_BATCH):
        chunk = ids[i : i + DELETE_BATCH]
        placeholders = ", ".join("?" for _ in chunk)
        resp = d1_query(token_box, f"DELETE FROM {table} WHERE id IN ({placeholders})", list(chunk))
        if not resp.get("success"):
            raise RuntimeError(f"delete failed on {table}: {resp.get('errors')}")
        deleted += resp["result"][0]["meta"]["changes"]
    return deleted


def main():
    import psycopg2

    apply = "--apply" in sys.argv
    include_large = "--include-large" in sys.argv
    only = None
    if "--tables" in sys.argv:
        only = {t.strip() for t in sys.argv[sys.argv.index("--tables") + 1].split(",")}

    tables = [
        (pg, d1, ft, wh)
        for pg, d1, ft, wh in ALL_TABLES
        if (only is None or d1 in only) and (include_large or only is not None or d1 not in LARGE_TABLES)
    ]
    if not tables:
        raise SystemExit("no tables selected")

    token_box = TokenBox()
    env = load_env(FOODCHARITY_ENV_PATH)
    conn = psycopg2.connect(
        host=env["DB_HOST"], dbname=env["DB_NAME"], user=env["DB_USER"], password=env["DB_PASS"],
        port=5432, options="-c default_transaction_read_only=on -c statement_timeout=600000",
    )
    cur = conn.cursor()

    print("%-28s %10s %10s %12s %12s" % ("table", "postgres", "d1", "stray-in-d1", "missing-in-d1"), flush=True)
    print("-" * 76, flush=True)

    total_stray = total_missing = total_deleted = 0
    t0 = time.monotonic()

    # ONE D1 TABLE CAN HAVE SEVERAL LOADER DEFINITIONS. foodbankarticle is in
    # both HOMEPAGE_TABLES (a featured-only slice, 171 rows) and
    # DASHBOARD_TABLES (the full 17,235), and what the ETL actually puts in
    # D1 is the UNION. Comparing against either definition alone reports
    # thousands of phantom strays -- 17,067 of them, on the first attempt.
    by_d1 = {}
    for pg_table, d1_table, from_table, where in tables:
        by_d1.setdefault(d1_table, []).append((pg_table, from_table, where))

    for d1_table, defs in by_d1.items():
        in_pg = set()
        failed = None
        for pg_table, from_table, where in defs:
            try:
                in_pg |= pg_ids(cur, pg_table, from_table, where)
            except psycopg2.Error as exc:
                conn.rollback()
                failed = str(exc).strip().splitlines()[0][:40]
                break
        if failed:
            print("%-28s  SKIPPED (postgres: %s)" % (d1_table, failed), flush=True)
            continue
        in_d1 = d1_ids(token_box, d1_table)

        stray = in_d1 - in_pg      # deleted in production, still served here
        missing = in_pg - in_d1    # never loaded; a load fixes it, not a delete

        print("%-28s %10d %10d %12d %12d" % (d1_table, len(in_pg), len(in_d1), len(stray), len(missing)), flush=True)
        total_stray += len(stray)
        total_missing += len(missing)

        if stray and apply and d1_table in DELETABLE:
            n = delete_from_d1(token_box, d1_table, stray)
            total_deleted += n
            print("%-28s  deleted %d" % ("", n), flush=True)
        elif stray and apply:
            print("%-28s  NOT deleted -- the port writes this table itself, see DELETABLE" % "", flush=True)
        elif stray:
            sample = sorted(stray)[:8]
            print("%-28s  ids: %s%s" % ("", sample, " ..." if len(stray) > len(sample) else ""), flush=True)

    cur.close()
    conn.close()

    print("-" * 76, flush=True)
    print(
        "stray in D1: %d%s | missing from D1: %d | %.0fs"
        % (
            total_stray,
            (" (deleted %d)" % total_deleted) if apply else " (report only -- pass --apply to delete)",
            total_missing,
            time.monotonic() - t0,
        ),
        flush=True,
    )
    if total_missing:
        print("\nmissing-in-d1 is NOT fixed by this script -- run extract_core.py for those tables.", flush=True)


if __name__ == "__main__":
    main()
