import { DatabaseSync } from "node:sqlite";
import { MIGRATIONS_SQL } from "@givefood/db/src/schema.testkit";
import { afterEach, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import type { Env } from "../../worker-configuration";

// handleNotifyNeedFirebase -- the mobile-app arm of the admin's Notify
// button (gfadmin/views.py:1999-2006), ported from
// send_firebase_notification() (givefood/utils/notifications.py:189-272).
//
// WHY THIS FILE IS WORTH ITS LENGTH. Every other notification channel has
// a person on the end of it who can say "I didn't get it". This one
// addresses an FCM TOPIC: there is no subscriber list to read back, no
// row stamped on success, no delivery receipt, and the handler catches
// every one of its own failures and returns normally so the queue
// consumer ACKS. A broken service-account credential therefore produces
// exactly one symptom in production -- a console.error nobody is reading
// -- and the jobs-dlq stays empty while every app notification silently
// stops. That is not hypothetical on this codebase: a Browser Rendering
// credential broke this way for a day. The assertions below are the only
// thing standing between that class of failure and nobody noticing, so
// they pin the LOG LINES as well as the behaviour: the log line is the
// entire operator-visible surface of this module.
//
// REAL EVERYTHING EXCEPT THE THINGS THAT LEAVE THE MACHINE. The database
// is a real in-memory SQLite carrying the REAL migrations (MIGRATIONS_SQL,
// not a transcribed CREATE TABLE -- getNeedById reads the
// `foodbankchange_full` VIEW, which migration 0019 drops and recreates, so
// a hand-copied fixture would have been wrong on the day it was pasted).
// getNeedById and getFoodbankNotifyTarget are the shipped packages/db
// functions running their real SQL. The RSA key is a real 2048-bit
// RSASSA-PKCS1-v1_5 key generated by WebCrypto in beforeAll, the assertion
// is really signed by the real jwt.ts, and this file VERIFIES that
// signature with the matching public key -- because "an assertion was
// sent" and "an assertion Google would accept was sent" are different
// claims, and only the second one keeps the notifications flowing. The
// payload is built by the real payload.ts over the real @givefood/models
// and @givefood/urls. Only `fetch` is a fake, because Google's token
// endpoint and FCM are the only things here that leave the machine.
//
// MUTATION-TESTED TWICE, per TESTING.md's convention: once when it was
// written, and again in an adversarial review pass that copied the repo
// into a scratchpad OUTSIDE it and broke, 84 ways, every module this file
// exercises -- needFirebase.ts, payload.ts, jwt.ts's RS256 half, the two
// packages/db reads it makes, and queues/jobs.ts, which it reaches through
// the real consumer at the bottom. 83 die. Notable ones, because each is a
// plausible edit rather than a random character swap: resolving the food
// bank from `msg.needId` instead of `need.foodbank_id` (24 tests red);
// binding `id + 1` inside getNeedById with its SQL text left untouched
// (29); importing `client_email` as the private key (48); naming the topic
// from the slug rather than the uuid (9); `aud` addressed to FCM rather
// than to the token endpoint (2); `iat` rounded instead of floored (2); the
// cache's 60-second slack dropped (2), its ttl read as milliseconds (2),
// the cache poisoned by a FAILED exchange (2), and the cache consulted with
// `>=` so an expired token is reused on the boundary (1); the token minted
// before the two database reads rather than after (6); `expires_in`'s
// `?? 3600` default removed, which turns the expiry into NaN and silently
// disables the cache (1); `Bearer ` dropped from the Authorization header
// (7); the `return` after an FCM error removed, so a failure also logs a
// success (1), and that same path made to THROW, which turns an acked
// message into three retries and a jobs-dlq entry (2); `message.ack()`
// deleted from the real consumer (5) and its `message.retry()` swapped for
// an ack (2); `break` softened to `continue` in the budget loop, which
// skips an oversized item and lists the ones behind it (1); the 4,000-byte
// budget widened to 4,096 (4) and measured in characters rather than UTF-8
// bytes (1); and both base64url substitutions dropped from the JWT encoder
// (1 each).
//
// The review pass found FIVE survivors, all now dead; each is named in the
// comment on the test that kills it, so the next reader knows what that
// test is for. They were: an error STATUS carrying an access_token (the
// `!res.ok` half of the token check was unasserted); the two AbortSignal
// timeouts swapped, or either one cut to milliseconds (the fetch stub saw
// only THAT a signal was passed); the payload read from the uncleaned
// `change_text_original` beside the published text (that column was NULL in
// every fixture); `env.SITE_DOMAIN` replaced by the production domain the
// fixture happens to set it to; and a second, contradictory error line
// logged after "is not valid JSON".
//
// ONE SURVIVES, recorded rather than chased, because catching it needs a
// fixture asserting against data that cannot occur: `!res.ok` on the FCM
// response widened to `res.status >= 400`. The two differ only for a 3xx,
// and `fetch` follows redirects by default, so no 3xx reaches that line.
//
// FRESH MODULE PER TEST. `cachedToken` is module-level state that lives
// for the isolate, which is the point of it -- but it would otherwise leak
// a token minted in one test into the next one, making the whole file
// order-dependent and the caching tests meaningless. vi.resetModules() +
// a dynamic import gives each test its own cold isolate, and the caching
// tests then make TWO calls inside one test, which is the only honest way
// to assert a cache.

type FirebaseModule = typeof import("./needFirebase");
type JobsModule = typeof import("../queues/jobs");

let handleNotifyNeedFirebase: FirebaseModule["handleNotifyNeedFirebase"];
let handleJobsQueue: JobsModule["handleJobsQueue"];

// ---------------------------------------------------------------------------
// Fixture
// ---------------------------------------------------------------------------

const SITE_DOMAIN = "https://www.givefood.org.uk";
const TOKEN_URL = "https://oauth2.googleapis.com/token";
const FCM_PREFIX = "https://fcm.googleapis.com/v1/projects/";
const PROJECT_ID = "givefood-test";
const CLIENT_EMAIL = "firebase-adminsdk-9zk2t@givefood-test.iam.gserviceaccount.com";
const ACCESS_TOKEN = "ya29.a0AfB_first-token";

// Salisbury's need is id 19 and Devizes' FOOD BANK is id 19, deliberately.
// `need.foodbank_id` and `msg.needId` are two numbers a few lines apart in
// this handler, and a fixture where the food bank being notified happens to
// share an id with the need would let `getFoodbankNotifyTarget(session,
// msg.needId)` pass every assertion in the file. With this arrangement that
// mutant notifies Devizes' topic about Salisbury's shopping list -- which is
// also the real-world shape of the mistake: a food bank's own subscribers
// being told about somebody else's need.
const SALISBURY_ID = 7;
const SALISBURY_UUID = "b0a1c2d3e4f5460788990a1b2c3d4e5f";
const DEVIZES_ID = 19;
const DEVIZES_UUID = "11112222333344445555666677778888";

const NEED_ID = 19; // foodbank 7 (Salisbury)
const DECOY_NEED_ID = 20; // foodbank 19 (Devizes)
const ORPHAN_NEED_ID = 21; // foodbank_id NULL
const DANGLING_NEED_ID = 22; // foodbank_id 4242, which does not exist

const NEED_TEXT = "Beans\nPasta\nTinned Tomatoes";

// The UNCLEANED text needcheck stored before a human edited the list, one
// column away from change_text in the same row. Every seeded need carries
// it, and it deliberately says something else entirely: with both columns
// holding the same words, a payload built from `need.change_text_original ??
// need.change_text` passed this whole file, and the sibling suite already
// guards the same confusion (needEmail.test.ts:801). With these words that
// mutant tells Salisbury's subscribers the food bank needs custard.
const ORIGINAL_TEXT = "Custard\nRice pudding\nSquash\nCoffee";

// A fixed instant with a FRACTIONAL second in it. `iat` is
// Math.floor(nowMs / 1000); a .750 offset is what makes a `Math.round`
// there visible, and an assertion whose iat is a second in the future is
// one Google rejects outright.
const NOW = Date.parse("2026-09-08T12:00:00.750Z");
const NOW_SEC = Math.floor(NOW / 1000);

let PRIVATE_KEY_PEM: string;
let PUBLIC_KEY: CryptoKey;

/** PKCS#8 DER as the PEM block a Google service account's `private_key` holds. */
function toPem(der: ArrayBuffer): string {
  const bytes = new Uint8Array(der);
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  const body = btoa(binary).replace(/(.{64})/g, "$1\n");
  return `-----BEGIN PRIVATE KEY-----\n${body}\n-----END PRIVATE KEY-----\n`;
}

beforeAll(async () => {
  // A REAL key, not a fixture string: importRs256Key() hands the PEM
  // straight to crypto.subtle.importKey, so anything that is not a genuine
  // PKCS#8 RSA key exercises only the error path. 2048 bits is what Google
  // issues, and generating one costs ~50 ms once for the whole file.
  const pair = (await crypto.subtle.generateKey(
    { name: "RSASSA-PKCS1-v1_5", modulusLength: 2048, publicExponent: new Uint8Array([1, 0, 1]), hash: "SHA-256" },
    true,
    ["sign", "verify"],
  )) as CryptoKeyPair;
  // `as ArrayBuffer`: exportKey is typed `ArrayBuffer | JsonWebKey` across
  // both its overloads, and only the "jwk" format returns the second.
  PRIVATE_KEY_PEM = toPem((await crypto.subtle.exportKey("pkcs8", pair.privateKey)) as ArrayBuffer);
  PUBLIC_KEY = pair.publicKey;
});

function serviceAccount(overrides: Record<string, unknown> = {}): string {
  return JSON.stringify({
    type: "service_account",
    project_id: PROJECT_ID,
    client_email: CLIENT_EMAIL,
    private_key: PRIVATE_KEY_PEM,
    ...overrides,
  });
}

// ---------------------------------------------------------------------------
// The database
// ---------------------------------------------------------------------------

type Bindable = null | number | bigint | string | Uint8Array;

interface Prepared {
  sql: string;
  params: Bindable[];
}

let db: DatabaseSync;
/** Every statement this handler actually ran, in order, with its binds. */
let prepared: Prepared[];
/** The bookmark mode each withSession() was asked for. */
let sessionModes: string[];

// The D1DatabaseSession surface packages/db uses, over node:sqlite -- the
// same shim shape as packages/db/src/notifySubscribers.test.ts's.
// Deliberately dumb: it forwards the SQL untouched so the ENGINE decides
// which row comes back, rather than this file re-implementing SQLite and
// then agreeing with itself.
function d1Session() {
  const statement = (sql: string, params: Bindable[]) => ({
    bind: (...next: unknown[]) => statement(sql, next as Bindable[]),
    first: async <T>() => {
      prepared.push({ sql, params });
      return (db.prepare(sql).get(...params) as T | undefined) ?? null;
    },
    all: async () => {
      prepared.push({ sql, params });
      return { results: db.prepare(sql).all(...params), success: true, meta: {} };
    },
    run: async () => {
      prepared.push({ sql, params });
      const info = db.prepare(sql).run(...params);
      return { success: true, meta: { changes: Number(info.changes), last_row_id: Number(info.lastInsertRowid) } };
    },
  });
  return { prepare: (sql: string) => statement(sql, []), getBookmark: () => null };
}

/** Every NOT NULL column 0001_core.sql declares on foodbank, filled to satisfy it. */
function seedFoodbank(id: number, uuid: string, name: string, slug: string): void {
  db.prepare(
    "INSERT INTO foodbank (id, uuid, name, slug, address, postcode, country, lat_lng, " +
      "charity_just_foodbank, contact_email, url, shopping_list_url, address_is_administrative, " +
      "is_closed, no_locations, days_between_needs, created, modified) " +
      "VALUES (?, ?, ?, ?, '1 High St', 'SP1 1AA', 'England', '51.0688,-1.7945', " +
      "0, 'info@example.org', 'https://example.org/', 'https://example.org/list/', 0, " +
      "0, 0, 14, '2020-01-01 00:00:00.000000', '2026-09-05 19:28:08.853000')",
  ).run(id, uuid, name, slug);
}

function seedNeed(id: number, foodbankId: number | null, changeText: string, published = 1): void {
  db.prepare(
    "INSERT INTO foodbankchange (id, need_id, foodbank_id, change_text, change_text_original, published, input_method, created, modified) " +
      "VALUES (?, ?, ?, ?, ?, ?, 'manual', '2026-09-08 11:59:00.000000', '2026-09-08 11:59:00.000000')",
  ).run(id, `need${String(id).padStart(28, "0")}`, foodbankId, changeText, ORIGINAL_TEXT, published);
}

/** The whole need row, as a plain object (node:sqlite hands back null-prototype rows). */
function needRow(id: number): Record<string, unknown> {
  return { ...(db.prepare("SELECT * FROM foodbankchange WHERE id = ?").get(id) as object) };
}

// ---------------------------------------------------------------------------
// The two things that leave the machine
// ---------------------------------------------------------------------------

interface FetchCall {
  url: string;
  method: string;
  headers: Record<string, string>;
  body: string;
  /** Whether the request carried an AbortSignal -- see the timeout test. */
  aborts: boolean;
}

interface StubInit {
  method?: string;
  headers?: Record<string, string>;
  body?: unknown;
  signal?: unknown;
}

let calls: FetchCall[];
let tokenReply: () => Response | Promise<Response>;
let fcmReply: () => Response | Promise<Response>;
/**
 * Every AbortSignal.timeout() the handler asked for, in call order. The
 * fetch stub can see THAT a request carried a signal but not how long it
 * runs for, and both requests carry one -- so swapping the token exchange's
 * 15s with the send's 20s, or cutting either to 20ms, was invisible to this
 * whole file until the argument itself was recorded.
 */
let timeoutsMs: number[];

const okToken = (overrides: Record<string, unknown> = {}) =>
  new Response(JSON.stringify({ access_token: ACCESS_TOKEN, expires_in: 3600, token_type: "Bearer", ...overrides }), {
    status: 200,
    headers: { "Content-Type": "application/json" },
  });

const okFcm = (name = "projects/givefood-test/messages/0:1757332800000000%abc") =>
  new Response(JSON.stringify({ name }), { status: 200, headers: { "Content-Type": "application/json" } });

let consoleError: ReturnType<typeof vi.spyOn>;
let consoleWarn: ReturnType<typeof vi.spyOn>;
let consoleLog: ReturnType<typeof vi.spyOn>;

beforeEach(async () => {
  db = new DatabaseSync(":memory:");
  db.exec(MIGRATIONS_SQL);
  seedFoodbank(SALISBURY_ID, SALISBURY_UUID, "Salisbury", "salisbury");
  seedFoodbank(DEVIZES_ID, DEVIZES_UUID, "Devizes", "devizes");
  seedNeed(NEED_ID, SALISBURY_ID, NEED_TEXT);
  seedNeed(DECOY_NEED_ID, DEVIZES_ID, "Nappies\nWashing powder");
  seedNeed(ORPHAN_NEED_ID, null, "Beans");
  seedNeed(DANGLING_NEED_ID, 4242, "Beans");

  prepared = [];
  sessionModes = [];
  calls = [];
  tokenReply = () => okToken();
  fcmReply = () => okFcm();

  vi.stubGlobal(
    "fetch",
    vi.fn(async (input: unknown, init: StubInit = {}): Promise<Response> => {
      const url = String(input);
      calls.push({
        url,
        method: init.method ?? "GET",
        headers: { ...(init.headers ?? {}) },
        body: init.body === undefined ? "" : String(init.body),
        aborts: init.signal !== undefined && init.signal !== null,
      });
      if (url === TOKEN_URL || url === ALTERNATE_TOKEN_URL) return tokenReply();
      if (url.startsWith(FCM_PREFIX)) return fcmReply();
      // An outbound call this file does not model is a test bug, and a
      // silent one if it merely returned an empty 200.
      throw new Error(`unmodelled fetch: ${url}`);
    }),
  );

  // AbortSignal.timeout stays REAL underneath the spy: the value handed to
  // `fetch` must still be a signal, and a stub returning something else
  // would test the stub. Only the argument is recorded.
  timeoutsMs = [];
  const realTimeout = AbortSignal.timeout.bind(AbortSignal);
  vi.spyOn(AbortSignal, "timeout").mockImplementation((ms: number) => {
    timeoutsMs.push(ms);
    return realTimeout(ms);
  });

  // Date.now() is the ONLY clock this module reads, and it reads it for the
  // JWT's iat/exp and for the token cache's expiry. Only Date is faked:
  // AbortSignal.timeout() must stay real, since a faked timer that never
  // advances would change what those signals do.
  vi.useFakeTimers({ toFake: ["Date"] });
  vi.setSystemTime(NOW);

  // This module narrates every degradation and nothing else. Silenced by
  // default (most of these tests ARE degradations) but kept as spies,
  // because for this channel the log line is the whole operator-visible
  // surface: there is no row written, no delivery receipt, and no retry.
  consoleError = vi.spyOn(console, "error").mockImplementation(() => {});
  consoleWarn = vi.spyOn(console, "warn").mockImplementation(() => {});
  consoleLog = vi.spyOn(console, "log").mockImplementation(() => {});

  vi.resetModules();
  ({ handleNotifyNeedFirebase } = await import("./needFirebase"));
  ({ handleJobsQueue } = await import("../queues/jobs"));
});

afterEach(() => {
  vi.unstubAllGlobals();
  vi.useRealTimers();
  vi.restoreAllMocks();
  db.close();
});

const ALTERNATE_TOKEN_URL = "https://oauth2.example.test/token";

function buildEnv(overrides: Record<string, unknown> = {}): Env {
  return {
    DB: {
      withSession: (mode: string) => {
        sessionModes.push(mode);
        return d1Session();
      },
    },
    SITE_DOMAIN,
    FIREBASE_SERVICE_ACCOUNT: serviceAccount(),
    ...overrides,
  } as unknown as Env;
}

/** The message routes/admin/needs.ts:248 enqueues, byte for byte. */
function message(needId: number = NEED_ID) {
  return { type: "notify-need-firebase" as const, needId };
}

async function notify(needId: number = NEED_ID, env: Env = buildEnv()): Promise<void> {
  return handleNotifyNeedFirebase(message(needId), env);
}

const tokenCalls = () => calls.filter((call) => call.url === TOKEN_URL || call.url === ALTERNATE_TOKEN_URL);
const fcmCalls = () => calls.filter((call) => call.url.startsWith(FCM_PREFIX));

/** The `message` object the handler POSTed to FCM. */
function sentMessage(index = 0): Record<string, unknown> {
  return JSON.parse(fcmCalls()[index]!.body) as Record<string, unknown>;
}

/** The service-account assertion out of the token request's form body. */
function assertionOf(index = 0): string {
  return new URLSearchParams(tokenCalls()[index]!.body).get("assertion")!;
}

// base64url decoded WITHOUT the module's own jwt.ts helpers. Decoding with
// the same code that encoded would agree with an encoder that had, say,
// forgotten the +/- substitution -- and Google would not.
function segmentBytes(segment: string): Uint8Array {
  const b64 = segment.replace(/-/g, "+").replace(/_/g, "/");
  const binary = atob(b64.padEnd(Math.ceil(b64.length / 4) * 4, "="));
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

function segmentJson(segment: string): Record<string, unknown> {
  return JSON.parse(new TextDecoder().decode(segmentBytes(segment))) as Record<string, unknown>;
}

// ===========================================================================
// The credential
// ===========================================================================

describe("the service-account credential -- the failure that is invisible by construction", () => {
  // notifications.py:170-172 warns and returns rather than raising, because
  // the other three channels are separate tasks and must still go out. The
  // level matters and is asserted: a Worker's logs are filtered by level, and
  // demoting this to console.log would remove the only trace that anything
  // was skipped.
  it("warns and does nothing at all when FIREBASE_SERVICE_ACCOUNT is unset", async () => {
    await expect(notify(NEED_ID, buildEnv({ FIREBASE_SERVICE_ACCOUNT: undefined }))).resolves.toBeUndefined();

    expect(consoleWarn).toHaveBeenCalledWith("notify-need-firebase: FIREBASE_SERVICE_ACCOUNT not set, skipping");
    expect(consoleError).not.toHaveBeenCalled();
    // No round trip, and no DATABASE round trip either: the credential check
    // is first, so a Worker deployed without the secret costs nothing per
    // message beyond the log line.
    expect(calls).toEqual([]);
    expect(prepared).toEqual([]);
  });

  // A secret that exists but is empty is what `wrangler secret put` leaves
  // behind when someone pipes it an empty file, and the guard is truthiness
  // rather than `=== undefined`, so this must take the same branch. If it
  // ever fell through instead, JSON.parse("") would raise a SyntaxError --
  // caught, but reported as "not valid JSON", which sends an operator
  // looking for a malformed secret rather than a missing one.
  it("treats an empty-string credential as unset, not as malformed JSON", async () => {
    await notify(NEED_ID, buildEnv({ FIREBASE_SERVICE_ACCOUNT: "" }));

    expect(consoleWarn).toHaveBeenCalledWith("notify-need-firebase: FIREBASE_SERVICE_ACCOUNT not set, skipping");
    expect(consoleError).not.toHaveBeenCalled();
    expect(calls).toEqual([]);
  });

  // notifications.py:174-177's json.JSONDecodeError branch, same non-fatal
  // shape. Returning normally is the load-bearing half: it means the queue
  // ACKS a message whose credential is unusable, so nothing accumulates in
  // jobs-dlq for anyone to notice.
  it("logs and returns for a credential that is not JSON", async () => {
    await expect(notify(NEED_ID, buildEnv({ FIREBASE_SERVICE_ACCOUNT: "{not json" }))).resolves.toBeUndefined();

    expect(consoleError).toHaveBeenCalledWith("notify-need-firebase: FIREBASE_SERVICE_ACCOUNT is not valid JSON");
    // ONE line, and it is that one. A mutant that logged this and then fell
    // through to the shape check added "is missing project_id/client_email/
    // private_key" underneath it, which is both false and actively
    // misleading -- it sends an operator looking for a truncated credential
    // rather than an unparseable one. For a channel whose entire
    // operator-visible surface is a log line, a second contradictory line is
    // the whole bug, and toHaveBeenCalledWith alone could not see it.
    expect(consoleError).toHaveBeenCalledTimes(1);
    expect(calls).toEqual([]);
    expect(prepared).toEqual([]);
  });

  // Valid JSON of the wrong shape -- what pasting the OAuth client secret,
  // or a truncated file, actually produces. Each field is checked
  // separately because the three are checked in one `if` and a dropped
  // clause is invisible unless the field it guards is missing on its own.
  for (const field of ["project_id", "client_email", "private_key"] as const) {
    it(`logs and returns when the credential has no ${field}`, async () => {
      await notify(NEED_ID, buildEnv({ FIREBASE_SERVICE_ACCOUNT: serviceAccount({ [field]: undefined }) }));

      expect(consoleError).toHaveBeenCalledWith(
        "notify-need-firebase: FIREBASE_SERVICE_ACCOUNT is missing project_id/client_email/private_key",
      );
      expect(calls).toEqual([]);
    });

    // The same guard reached through the other falsy spelling. An empty
    // project_id would otherwise POST to
    // `https://fcm.googleapis.com/v1/projects//messages:send`, which is a
    // 404 from Google and one more error log nobody reads.
    it(`treats an empty-string ${field} as missing`, async () => {
      await notify(NEED_ID, buildEnv({ FIREBASE_SERVICE_ACCOUNT: serviceAccount({ [field]: "" }) }));

      expect(consoleError).toHaveBeenCalledWith(
        "notify-need-firebase: FIREBASE_SERVICE_ACCOUNT is missing project_id/client_email/private_key",
      );
      expect(calls).toEqual([]);
    });
  }

  // A whole JSON blob with the right keys but a private_key that is not a
  // PKCS#8 RSA key -- a re-wrapped or truncated secret, which is exactly
  // what a credential rotation gone wrong looks like. importRs256Key throws
  // and the error is caught: NO fetch at all, not even the token exchange.
  it("logs and returns when the private key cannot be imported, without any round trip", async () => {
    const broken = serviceAccount({ private_key: "-----BEGIN PRIVATE KEY-----\nbm90LWEta2V5\n-----END PRIVATE KEY-----\n" });

    await expect(notify(NEED_ID, buildEnv({ FIREBASE_SERVICE_ACCOUNT: broken }))).resolves.toBeUndefined();

    expect(consoleError).toHaveBeenCalledWith(
      "notify-need-firebase: could not sign the service-account assertion",
      expect.any(Error),
    );
    expect(calls).toEqual([]);
  });
});

// ===========================================================================
// The rows
// ===========================================================================

describe("the rows it reads", () => {
  // The bookmark mode is a deliberate choice shared by every notify
  // consumer: the need was written by the admin request that enqueued this
  // message, so a session that may read a stale replica can miss it. Pinned
  // because it is invisible in the shipped code's behaviour and would be
  // silently "tidied" to a plain withSession().
  it("opens a first-unconstrained session", async () => {
    await notify();

    expect(sessionModes).toEqual(["first-unconstrained"]);
  });

  // The dispatcher hands this handler a needId with no validation
  // (queues/jobs.ts:70 casts the body), so a need deleted between the
  // Notify press and the message being picked up lands here. It must not
  // throw: throwing would retry the message three times and then park it in
  // jobs-dlq, for a need that will never come back.
  it("logs and returns for a need that no longer exists", async () => {
    await expect(notify(4242)).resolves.toBeUndefined();

    expect(consoleError).toHaveBeenCalledWith("notify-need-firebase: need 4242 is missing or has no food bank");
    expect(calls).toEqual([]);
  });

  // foodbankchange.foodbank_id is NULLABLE in the real schema (0001_core.sql)
  // and the admin's own Notify handler refuses this case with a 400 -- but
  // the queue message carries only an id, so the consumer has to make the
  // same check for itself. The `?.` and the `!` are one expression; a need
  // with no food bank takes the same branch as a need that is gone.
  it("logs and returns for a need with no food bank", async () => {
    await notify(ORPHAN_NEED_ID);

    expect(consoleError).toHaveBeenCalledWith(`notify-need-firebase: need ${ORPHAN_NEED_ID} is missing or has no food bank`);
    expect(calls).toEqual([]);
  });

  // No FK is declared between foodbankchange and foodbank (the two
  // reference each other circularly -- see 0001_core.sql's note on
  // latest_need_id), so a dangling foodbank_id is reachable. The message
  // names the FOOD BANK id, not the need id, which is what an operator
  // needs to chase it.
  it("logs and returns when the need's food bank is gone", async () => {
    await notify(DANGLING_NEED_ID);

    expect(consoleError).toHaveBeenCalledWith("notify-need-firebase: food bank 4242 not found");
    expect(calls).toEqual([]);
  });

  // THE ROW IT ASKED FOR, not the first row in the table. Both selects are
  // `WHERE id = ?`; a predicate that stopped binding would hand back need 19
  // by luck here and Devizes' food bank by luck elsewhere, so the fixture
  // seeds four needs and two food banks and the assertions name the values
  // that could only have come from the right pair.
  it("reads the need the message names, and its own food bank", async () => {
    await notify(DECOY_NEED_ID);

    expect(prepared.map((p) => p.params)).toEqual([[DECOY_NEED_ID], [DEVIZES_ID]]);
    expect(sentMessage().message).toMatchObject({
      topic: `foodbank-${DEVIZES_UUID}`,
      notification: { title: "Devizes needs 2 items", body: "Nappies, Washing powder" },
      data: { foodbank_slug: "devizes" },
    });
  });

  // The shape of the mistake this fixture exists to catch: `msg.needId`
  // where `need.foodbank_id` belongs. Need 19 belongs to food bank 7, and
  // food bank 19 is a different food bank -- so the transposition resolves
  // cleanly, sends successfully, logs a success, and tells Devizes'
  // subscribers about Salisbury's shopping list.
  it("resolves the food bank through need.foodbank_id, not through the need's own id", async () => {
    await notify(NEED_ID);

    expect(prepared[1]!.params).toEqual([SALISBURY_ID]);
    expect(sentMessage().message).toMatchObject({ topic: `foodbank-${SALISBURY_UUID}` });
  });

  // The need is read BEFORE the credential is exchanged. Not cosmetic: a
  // Notify pressed on a need that was then deleted would otherwise cost an
  // RSA signature and a round trip to Google per message, and on a DLQ
  // replay that is a burst of them.
  it("costs no token exchange when the need cannot be resolved", async () => {
    await notify(4242);

    expect(tokenCalls()).toEqual([]);
  });

  // NOT GATED ON `published`. The admin's own Notify handler refuses an
  // unpublished need (routes/admin/needs.ts:230). Django is WEAKER, not the
  // same: need_notifications (gfadmin/views.py:1980-2007) makes no
  // publication check at all -- it is the template that hides the button
  // ({% if need.published %} around the form, gfadmin/templates/admin/
  // need.html:122-127), so a POST to the Django URL would notify a draft.
  // Either way this consumer has no opinion of its own, and pinning that
  // means a future producer cannot quietly start notifying drafts without
  // this test going red first.
  it("sends for an unpublished need, because the consumer does not re-check publication", async () => {
    db.prepare("UPDATE foodbankchange SET published = 0 WHERE id = ?").run(NEED_ID);

    await notify();

    // The CONTENT, not just the count: a length check alone would also pass
    // if an unpublished need were sent with some other food bank's list, and
    // "it sent something" is not the claim being pinned here.
    expect(fcmCalls()).toHaveLength(1);
    expect(sentMessage().message).toMatchObject({
      topic: `foodbank-${SALISBURY_UUID}`,
      notification: { title: "Salisbury needs 3 items", body: "Beans, Pasta, Tinned Tomatoes" },
    });
  });
});

// ===========================================================================
// The token exchange
// ===========================================================================

describe("the OAuth2 token exchange -- what firebase-admin's credential layer does for Django", () => {
  it("POSTs the JWT-bearer grant, form-encoded, to Google's token endpoint before touching FCM", async () => {
    await notify();

    expect(calls.map((c) => c.url)).toEqual([TOKEN_URL, `${FCM_PREFIX}${PROJECT_ID}/messages:send`]);
    const token = tokenCalls()[0]!;
    expect(token.method).toBe("POST");
    expect(token.headers).toEqual({ "Content-Type": "application/x-www-form-urlencoded" });
    // urn:ietf:params:oauth:grant-type:jwt-bearer, RFC 7523 §2.1. Anything
    // else is a 400 from Google, and this handler's only response to a 400
    // is a log line.
    const form = new URLSearchParams(token.body);
    expect(form.get("grant_type")).toBe("urn:ietf:params:oauth:grant-type:jwt-bearer");
    expect(form.get("assertion")).toBeTruthy();
    expect([...form.keys()].sort()).toEqual(["assertion", "grant_type"]);
  });

  // THE ASSERTION IS THE CREDENTIAL. Every claim here is one Google
  // validates and rejects the whole exchange over, and a rejection reaches
  // production as a console.error and nothing else.
  it("signs an RS256 assertion whose claims are the ones Google validates", async () => {
    await notify();

    const [header, claims] = assertionOf().split(".");
    expect(segmentJson(header!)).toEqual({ alg: "RS256", typ: "JWT" });
    expect(segmentJson(claims!)).toEqual({
      iss: CLIENT_EMAIL,
      scope: "https://www.googleapis.com/auth/firebase.messaging",
      // `aud` is the TOKEN ENDPOINT, not the FCM API: the assertion is
      // addressed to whoever exchanges it. Naming fcm.googleapis.com here
      // is a plausible edit and an invalid_grant from Google.
      aud: TOKEN_URL,
      iat: NOW_SEC,
      exp: NOW_SEC + 3600,
    });
  });

  // `iat` is FLOORED, not rounded. The fixture clock is .750 of a second
  // past the tick precisely so that a Math.round() here would produce an
  // iat one second in the FUTURE, which Google rejects as
  // "Invalid JWT: Token must be a short-lived token".
  it("floors iat to the second rather than rounding it", async () => {
    await notify();

    const claims = segmentJson(assertionOf().split(".")[1]!);
    expect(claims.iat).toBe(NOW_SEC);
    // The guard on the guard: if the fixture clock ever became a whole
    // number of seconds, the assertion above would stop proving anything.
    expect(NOW_SEC * 1000).not.toBe(NOW);
  });

  // A real signature check with the real public half of the real key.
  // "An assertion was sent" and "an assertion Google will accept" are
  // different claims, and only the second one keeps notifications flowing.
  it("signs the assertion with the service account's own key", async () => {
    await notify();

    const assertion = assertionOf();
    const signature = segmentBytes(assertion.split(".")[2]!);
    const signed = new TextEncoder().encode(assertion.slice(0, assertion.lastIndexOf(".")));

    await expect(
      crypto.subtle.verify(
        "RSASSA-PKCS1-v1_5",
        PUBLIC_KEY,
        signature as unknown as ArrayBuffer,
        signed as unknown as ArrayBuffer,
      ),
    ).resolves.toBe(true);
  });

  // base64URL, not base64: a "+", "/" or "=" in any segment makes the JWT
  // unparseable to Google. jwt.ts does the substitution and the strip, and
  // this is the assertion that says so without going through jwt.ts's own
  // decoder to find out.
  it("emits base64url segments with no padding", async () => {
    await notify();

    expect(assertionOf()).toMatch(/^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/);
  });

  // Service-account JSON may carry its own token_uri (Google has issued
  // more than one over the years, and an emulator sets its own). The
  // override has to move BOTH the request and the `aud` claim -- moving
  // only the request produces an assertion the new endpoint rejects.
  it("honours a token_uri in the credential, in the request and in aud alike", async () => {
    await notify(NEED_ID, buildEnv({ FIREBASE_SERVICE_ACCOUNT: serviceAccount({ token_uri: ALTERNATE_TOKEN_URL }) }));

    expect(tokenCalls()[0]!.url).toBe(ALTERNATE_TOKEN_URL);
    expect(segmentJson(assertionOf().split(".")[1]!).aud).toBe(ALTERNATE_TOKEN_URL);
    expect(fcmCalls()).toHaveLength(1);
  });

  // Both outbound calls carry an AbortSignal. A hung connection to Google
  // would otherwise hold the message for the consumer's whole timeout and
  // take the batch's other nine messages down with it.
  it("bounds both outbound calls with a timeout: 15s on the exchange, 20s on the send", async () => {
    await notify();

    expect(calls.map((c) => c.aborts)).toEqual([true, true]);
    // THE VALUES, not merely their presence. With only the booleans above,
    // two plausible careless edits survived this entire file: swapping the
    // two durations (20s on the exchange, 15s on the send), and cutting the
    // send's to 20ms -- which would abort every notification the moment FCM
    // was fractionally slow, and report it as "send failed" with no status.
    expect(timeoutsMs).toEqual([15_000, 20_000]);
  });
});

describe("the token cache -- one RSA signature and one round trip per hour, not per message", () => {
  // firebase-admin caches the same way (its initialize_app is guarded by
  // get_app()). Minting per message would add an RSA signature and a round
  // trip to Google to every notification for no benefit.
  it("mints once and reuses the token for the next message in the same isolate", async () => {
    await notify(NEED_ID);
    await notify(DECOY_NEED_ID);

    expect(tokenCalls()).toHaveLength(1);
    expect(fcmCalls()).toHaveLength(2);
    expect(fcmCalls()[1]!.headers.Authorization).toBe(`Bearer ${ACCESS_TOKEN}`);
  });

  // The 60 seconds of slack the module's comment claims, asserted at both
  // sides of the boundary. A token used one second past its life is a 401
  // from FCM, which this handler reports as a log line and nothing else --
  // so the slack is the difference between a refreshed token and an hour of
  // silently dropped notifications.
  it("reuses the token right up to expires_in minus 60 seconds", async () => {
    await notify();
    vi.setSystemTime(NOW + 3600_000 - 60_000 - 1);
    await notify();

    expect(tokenCalls()).toHaveLength(1);
  });

  it("re-mints the moment the 60-second slack is reached", async () => {
    await notify();
    tokenReply = () => okToken({ access_token: "ya29.a0AfB_second-token" });
    vi.setSystemTime(NOW + 3600_000 - 60_000);
    await notify();

    expect(tokenCalls()).toHaveLength(2);
    expect(fcmCalls()[1]!.headers.Authorization).toBe("Bearer ya29.a0AfB_second-token");
  });

  // Google always sends expires_in, but the `?? 3600` is the difference
  // between a sane default and `NaN`: `nowMs + (undefined - 60) * 1000` is
  // NaN, and `NaN > nowMs` is false, so a missing default would silently
  // turn the cache off and mint per message.
  it("falls back to an hour when the response omits expires_in", async () => {
    tokenReply = () => new Response(JSON.stringify({ access_token: ACCESS_TOKEN }), { status: 200 });

    await notify();
    vi.setSystemTime(NOW + 3600_000 - 60_000 - 1);
    await notify();

    expect(tokenCalls()).toHaveLength(1);
  });

  // A token shorter-lived than the slack caches as ALREADY EXPIRED, so the
  // next message mints again rather than reusing something Google would
  // reject. Degenerate, but it is the arithmetic's edge and it degrades the
  // safe way.
  it("never reuses a token whose lifetime is shorter than the slack", async () => {
    tokenReply = () => okToken({ expires_in: 30 });

    await notify(NEED_ID);
    await notify(DECOY_NEED_ID);

    expect(tokenCalls()).toHaveLength(2);
  });

  // A failed exchange must not poison the cache: `cachedToken` is assigned
  // only on the success path. If a transient 503 cached a null token, every
  // subsequent message in that isolate would send `Bearer null` and FCM
  // would 401 them all -- an hour of silence from one bad second.
  it("does not cache anything when the exchange fails, and recovers on the next message", async () => {
    tokenReply = () => new Response(JSON.stringify({ error: "internal_failure" }), { status: 503 });

    await notify(NEED_ID);
    expect(fcmCalls()).toEqual([]);

    tokenReply = () => okToken();
    await notify(DECOY_NEED_ID);

    expect(tokenCalls()).toHaveLength(2);
    expect(fcmCalls()).toHaveLength(1);
    expect(fcmCalls()[0]!.headers.Authorization).toBe(`Bearer ${ACCESS_TOKEN}`);
  });

  // SUSPECT, pinned as-is. The cache is "keyed by nothing" -- the module
  // says so, on the grounds that one Worker has one service account. That
  // holds today, but it means a redeployed Worker whose secret was rotated
  // mid-isolate keeps signing with the OLD project's token while addressing
  // the NEW project's URL: the second account here has a private key that
  // cannot even be imported, and no signing is attempted because the token
  // is already in hand. FCM answers 403 and the only symptom is a log line.
  // Reported, not fixed.
  it("reuses a cached token even after the credential itself changes", async () => {
    await notify(NEED_ID);

    const rotated = serviceAccount({
      project_id: "givefood-rotated",
      private_key: "-----BEGIN PRIVATE KEY-----\nbm90LWEta2V5\n-----END PRIVATE KEY-----\n",
    });
    await notify(DECOY_NEED_ID, buildEnv({ FIREBASE_SERVICE_ACCOUNT: rotated }));

    expect(tokenCalls()).toHaveLength(1);
    expect(fcmCalls()[1]!.url).toBe(`${FCM_PREFIX}givefood-rotated/messages:send`);
    expect(fcmCalls()[1]!.headers.Authorization).toBe(`Bearer ${ACCESS_TOKEN}`);
  });
});

describe("when the token exchange fails", () => {
  // The exact shape of the credential outage this file exists for: three
  // arguments, so an operator grepping the logs gets Google's own reason
  // ("invalid_grant", "Invalid JWT Signature") rather than just a status.
  it("logs the status and Google's own reason, and does not call FCM", async () => {
    tokenReply = () =>
      new Response(JSON.stringify({ error: "invalid_grant", error_description: "Invalid JWT Signature." }), { status: 400 });

    await expect(notify()).resolves.toBeUndefined();

    expect(consoleError).toHaveBeenCalledWith(
      "notify-need-firebase: token exchange failed (HTTP 400)",
      "invalid_grant",
      "Invalid JWT Signature.",
    );
    expect(fcmCalls()).toEqual([]);
    expect(consoleLog).not.toHaveBeenCalled();
  });

  // A 200 with no access_token in it. `!res.ok || !payload.access_token` is
  // one condition; dropping the second half would send `Bearer undefined`
  // to FCM and turn a clean failure into a 401 per message.
  it("treats a 200 with no access_token as a failure", async () => {
    tokenReply = () => new Response(JSON.stringify({ token_type: "Bearer", expires_in: 3600 }), { status: 200 });

    await notify();

    expect(consoleError).toHaveBeenCalledWith(
      "notify-need-firebase: token exchange failed (HTTP 200)",
      undefined,
      undefined,
    );
    expect(fcmCalls()).toEqual([]);
  });

  // The STATUS is load-bearing on its own. `!res.ok || !payload.access_token`
  // is one condition and the file used to assert only the second half of it,
  // so narrowing the check to `!payload.access_token` -- a tidy-looking edit,
  // since the token is what the function returns -- survived every test here.
  // What it costs: a token minted from an ERROR response is cached for an
  // hour and presented to FCM, which 401s every message in the isolate. The
  // body below is not something Google sends; it is the smallest input that
  // makes the two halves of that condition distinguishable, and the
  // assertions are what the shipped code does with it today.
  it("treats an error status as a failure even when the body carries an access_token", async () => {
    tokenReply = () =>
      new Response(JSON.stringify({ access_token: ACCESS_TOKEN, expires_in: 3600 }), { status: 503 });

    await notify(NEED_ID);

    expect(consoleError).toHaveBeenCalledWith(
      "notify-need-firebase: token exchange failed (HTTP 503)",
      undefined,
      undefined,
    );
    expect(fcmCalls()).toEqual([]);
    // And nothing was cached from it: the next message mints again rather
    // than presenting a token the exchange never actually granted.
    tokenReply = () => okToken();
    await notify(DECOY_NEED_ID);
    expect(tokenCalls()).toHaveLength(2);
    expect(fcmCalls()[0]!.headers.Authorization).toBe(`Bearer ${ACCESS_TOKEN}`);
  });

  it("logs and returns when Google cannot be reached at all", async () => {
    tokenReply = () => {
      throw new TypeError("Network connection lost.");
    };

    await expect(notify()).resolves.toBeUndefined();

    expect(consoleError).toHaveBeenCalledWith("notify-need-firebase: token exchange could not be reached", expect.any(TypeError));
    expect(fcmCalls()).toEqual([]);
  });

  // SUSPECT, pinned as-is. `res.json()` is awaited BEFORE `res.ok` is
  // consulted, so an error page that is not JSON -- a proxy's HTML 502, a
  // captive portal -- is reported as "could not be reached" and the HTTP
  // status never appears in the logs at all. The handling is otherwise
  // identical (log, return, ack), so this costs diagnosis rather than
  // behaviour. Reported, not fixed.
  it("reports a non-JSON error page as unreachable, losing the status code", async () => {
    tokenReply = () => new Response("<html><body>502 Bad Gateway</body></html>", { status: 502 });

    await notify();

    expect(consoleError).toHaveBeenCalledWith("notify-need-firebase: token exchange could not be reached", expect.any(Error));
    expect(consoleError).not.toHaveBeenCalledWith(
      expect.stringContaining("token exchange failed"),
      expect.anything(),
      expect.anything(),
    );
    expect(fcmCalls()).toEqual([]);
  });
});

// ===========================================================================
// The message
// ===========================================================================

describe("the FCM v1 message -- notifications.py:238-269's messaging.Message, field for field", () => {
  // toEqual over the WHOLE body, not toMatchObject: an extra, renamed or
  // dropped key is the failure. The notification/data/webpush split is not
  // redundancy -- `notification` is what a native app renders, `webpush`
  // overrides it for FCM's own browser transport, and `data` is what a
  // handler reads programmatically -- so a field lost from one of the three
  // is a channel that silently renders wrong while the other two look fine.
  it("sends the three-way notification/data/webpush message to the food bank's topic", async () => {
    await notify();

    expect(sentMessage()).toEqual({
      message: {
        topic: `foodbank-${SALISBURY_UUID}`,
        notification: { title: "Salisbury needs 3 items", body: "Beans, Pasta, Tinned Tomatoes" },
        data: { foodbank_slug: "salisbury" },
        webpush: {
          notification: {
            title: "Salisbury needs 3 items",
            body: "Beans, Pasta, Tinned Tomatoes",
            // ROOT-RELATIVE, exactly as Django has it (notifications.py:249-250):
            // the service worker resolves it against the page origin, and an
            // absolute URL here breaks the day the site moves domain.
            icon: "/static/img/notificationicon.svg",
            badge: "/static/img/notificationicon.svg",
          },
          fcm_options: { link: `${SITE_DOMAIN}/needs/at/salisbury/` },
          data: { foodbank_slug: "salisbury", click_action: `${SITE_DOMAIN}/needs/at/salisbury/` },
        },
      },
    });
  });

  it("addresses the v1 send endpoint for the credential's own project, as the bearer of the minted token", async () => {
    await notify();

    const fcm = fcmCalls()[0]!;
    expect(fcm.url).toBe(`https://fcm.googleapis.com/v1/projects/${PROJECT_ID}/messages:send`);
    expect(fcm.method).toBe("POST");
    expect(fcm.headers).toEqual({ Authorization: `Bearer ${ACCESS_TOKEN}`, "Content-Type": "application/json" });
  });

  // The topic is the food bank's UUID, and the apps subscribe themselves to
  // it: get the topic wrong and the send succeeds, FCM reports a message
  // name, and not one phone is listening. There is no subscriber count to
  // notice the absence of, which is why this is asserted from the seeded
  // uuid rather than from the row the handler read.
  it("names the topic from the food bank's uuid, not its id or slug", async () => {
    await notify();

    const topic = (sentMessage().message as Record<string, unknown>).topic;
    expect(topic).toBe("foodbank-b0a1c2d3e4f5460788990a1b2c3d4e5f");
    // The two plausible wrong spellings, named rather than pattern-matched:
    // the uuid is hex, so "does not contain 7" would be false for the right
    // answer too.
    expect(topic).not.toBe("foodbank-salisbury");
    expect(topic).not.toBe(`foodbank-${SALISBURY_ID}`);
  });

  // FCM v1 REJECTS a non-string `data` value where the legacy API coerced
  // it. Both maps are string-valued today; this asserts it stays that way,
  // because a number slipped into either one is a 400 for every message.
  it("keeps every data value a string, as v1 requires", async () => {
    await notify();

    const msg = sentMessage().message as Record<string, Record<string, unknown>>;
    for (const value of Object.values(msg.data!)) expect(typeof value).toBe("string");
    for (const value of Object.values((msg.webpush!.data as Record<string, unknown>)!)) expect(typeof value).toBe("string");
  });

  // Django's own asymmetry, checked against all three call sites rather
  // than harmonised: the title uses foodbank.NAME (not full_name(), which
  // the email subject uses) and the RAW count (not apnumber()'s words). One
  // item really does read "needs 1 items".
  it("titles with the plain name and the raw count, ungrammatical singular included", async () => {
    db.prepare("UPDATE foodbankchange SET change_text = ? WHERE id = ?").run("Beans", NEED_ID);

    await notify();

    expect((sentMessage().message as Record<string, Record<string, string>>).notification!.title).toBe("Salisbury needs 1 items");
  });

  // The "Nothing" sentinel. no_items() special-cases it to 0 while
  // change_list() does not, so the notification reads "needs 0 items" with
  // the word "Nothing" as its body -- which is what Django sends today. The
  // admin only offers Notify on a need a human published, so this is a
  // reviewer's decision rather than a bug to paper over in the port.
  it("sends a 'Nothing' need as '0 items' with 'Nothing' as the body", async () => {
    db.prepare("UPDATE foodbankchange SET change_text = 'Nothing' WHERE id = ?").run(NEED_ID);

    await notify();

    expect((sentMessage().message as Record<string, Record<string, string>>).notification).toEqual({
      title: "Salisbury needs 0 items",
      body: "Nothing",
    });
  });

  // change_list() is the RAW split -- blank lines included. A need whose
  // text has a trailing newline notifies with a trailing ", " in the body,
  // and counts the blank as an item. Django does exactly this; pinned so
  // the port cannot quietly start filtering and diverge.
  it("keeps blank lines, in the count and in the body", async () => {
    db.prepare("UPDATE foodbankchange SET change_text = ? WHERE id = ?").run("Beans\n\nPasta\n", NEED_ID);

    await notify();

    expect((sentMessage().message as Record<string, Record<string, string>>).notification).toEqual({
      title: "Salisbury needs 4 items",
      body: "Beans, , Pasta, ",
    });
  });

  // notifications.py:220's 4,000-byte budget ("Firebase has a 4KB limit ...
  // we'll be conservative"). 45 items of 99 characters: 39 of them join to
  // 3,937 bytes and the 40th would make 4,038, so the body carries 39 while
  // the TITLE still says 45. That asymmetry is Django's too.
  it("truncates the body at 4,000 bytes, on an item boundary, leaving the count alone", async () => {
    const item = "A".repeat(99);
    db.prepare("UPDATE foodbankchange SET change_text = ? WHERE id = ?").run(Array(45).fill(item).join("\n"), NEED_ID);

    await notify();

    const notification = (sentMessage().message as Record<string, Record<string, string>>).notification!;
    expect(notification.title).toBe("Salisbury needs 45 items");
    expect(notification.body).toBe(Array(39).fill(item).join(", "));
    expect(new TextEncoder().encode(notification.body!).length).toBe(3937);
    // Whole items only -- never a half-written food item on somebody's
    // lock screen.
    expect(notification.body!.endsWith(item)).toBe(true);
  });

  // THE BUDGET IS INCLUSIVE, and 4,000 is the number. 87 items of 44
  // characters join to exactly 4,000 bytes, so this is the one fixture in
  // which `> budget` and `>= budget` disagree -- the second drops an item
  // that fits. It also pins the constant itself: at Firebase's real 4,096
  // the same text would carry 89 items, so a "the limit is 4KB, surely"
  // edit to notifications.py:220's deliberately conservative 4,000 shows up
  // here rather than as an occasional rejected message in production.
  it("keeps an item that lands exactly on the 4,000-byte budget", async () => {
    const item = "B".repeat(44);
    db.prepare("UPDATE foodbankchange SET change_text = ? WHERE id = ?").run(Array(90).fill(item).join("\n"), NEED_ID);

    await notify();

    const notification = (sentMessage().message as Record<string, Record<string, string>>).notification!;
    expect(notification.body).toBe(Array(87).fill(item).join(", "));
    expect(new TextEncoder().encode(notification.body!).length).toBe(4000);
  });

  // BYTES, NOT CHARACTERS, which is the one thing separating this builder
  // from the web push one (200 CHARACTERS). Two items of 1,000 "€" are
  // 2,002 characters -- comfortably inside 4,000 -- but 6,002 bytes, so
  // only the first survives. A char-counting mutant sends both and FCM
  // rejects the message outright.
  it("measures the budget in UTF-8 bytes, so multi-byte items count for more", async () => {
    const item = "€".repeat(1000);
    db.prepare("UPDATE foodbankchange SET change_text = ? WHERE id = ?").run(`${item}\n${item}`, NEED_ID);

    await notify();

    const notification = (sentMessage().message as Record<string, Record<string, string>>).notification!;
    expect(notification.body).toBe(item);
    expect(notification.body!.length).toBe(1000);
    expect(new TextEncoder().encode(notification.body!).length).toBe(3000);
  });

  // SUSPECT, pinned as-is. A single item bigger than the whole budget
  // leaves the body EMPTY -- the loop breaks before anything is kept -- and
  // the notification is sent anyway: a phone buzzes with "Salisbury needs 1
  // items" and no items. Django's loop has the same shape, so this is
  // ported behaviour rather than a port bug, and a 4,000-byte single line
  // is not something a reviewer would publish. Reported, not fixed.
  it("sends an empty body rather than nothing when the first item alone busts the budget", async () => {
    db.prepare("UPDATE foodbankchange SET change_text = ? WHERE id = ?").run("A".repeat(4001), NEED_ID);

    await notify();

    expect((sentMessage().message as Record<string, Record<string, string>>).notification).toEqual({
      title: "Salisbury needs 1 items",
      body: "",
    });
    expect(fcmCalls()).toHaveLength(1);
  });

  // STOPS at the first item that does not fit; it does not skip it and
  // carry on packing the shorter ones behind it. Django's loop breaks
  // ("Can't fit any more items", notifications.py:229-231) and the port
  // must too: a body that silently omitted item 12 while listing items 13
  // and 14 would look perfectly plausible on a phone and be a shopping
  // list nobody can act on. Every other truncation test here happens to
  // put the long items last, so this is the only fixture in which `break`
  // and `continue` differ at all.
  it("stops at the first item too big to fit rather than skipping it", async () => {
    db.prepare("UPDATE foodbankchange SET change_text = ? WHERE id = ?").run(`${"A".repeat(4001)}\nBeans`, NEED_ID);

    await notify();

    expect((sentMessage().message as Record<string, Record<string, string>>).notification).toEqual({
      title: "Salisbury needs 2 items",
      body: "",
    });
  });

  // The link is SITE_DOMAIN + the reversed wfbn:foodbank route. Concatenated
  // raw, so the binding must carry no trailing slash: this asserts the
  // shipped value's shape end to end rather than trusting the join.
  it("links to the food bank's own needs page on the configured domain", async () => {
    await notify();

    const webpush = (sentMessage().message as Record<string, Record<string, Record<string, string>>>).webpush!;
    expect(webpush.fcm_options!.link).toBe("https://www.givefood.org.uk/needs/at/salisbury/");
    expect(webpush.data!.click_action).toBe("https://www.givefood.org.uk/needs/at/salisbury/");
  });

  // ...and the domain comes from the BINDING. The fixture's SITE_DOMAIN is
  // the production one (workers/jobs/wrangler.jsonc:80), which makes
  // `${env.SITE_DOMAIN}` and a hard-coded "https://www.givefood.org.uk"
  // indistinguishable in every other assertion in this file -- that mutant
  // survived it. The second domain here is arbitrary; all that matters is
  // that it is not the one the rest of the file uses, so a baked-in domain
  // shows up as a link pointing at the wrong site rather than as nothing.
  it("takes the link's domain from the SITE_DOMAIN binding, not a baked-in one", async () => {
    await notify(NEED_ID, buildEnv({ SITE_DOMAIN: "https://gf-preview.example.test" }));

    const webpush = (sentMessage().message as Record<string, Record<string, Record<string, string>>>).webpush!;
    expect(webpush.fcm_options!.link).toBe("https://gf-preview.example.test/needs/at/salisbury/");
    expect(webpush.data!.click_action).toBe("https://gf-preview.example.test/needs/at/salisbury/");
  });

  // change_text is the PUBLISHED list; change_text_original is the uncleaned
  // text needcheck stored beside it, one column away in the same row. Every
  // need in this fixture carries a different one (ORIGINAL_TEXT), because
  // while that column was NULL a payload built from `need.change_text_original
  // ?? need.change_text` passed the whole file. The sibling email channel
  // guards the same confusion (needEmail.test.ts:801); it is a live enough
  // mistake in this schema to be worth guarding twice.
  it("notifies about the published change_text, not the uncleaned original beside it", async () => {
    expect(needRow(NEED_ID).change_text_original).toBe(ORIGINAL_TEXT);

    await notify();

    expect((sentMessage().message as Record<string, Record<string, string>>).notification).toEqual({
      title: "Salisbury needs 3 items",
      body: "Beans, Pasta, Tinned Tomatoes",
    });
  });

  // One HTTP call per NEED, not per subscriber: FCM addresses a topic and
  // the server holds no device list. mobilesubscriber exists in the schema
  // and is the analytics record the /mobsub/ endpoint writes -- treating it
  // as the send list would notify nobody, so this asserts the table is
  // never read.
  it("sends exactly one request and never reads the mobilesubscriber table", async () => {
    await notify();

    expect(fcmCalls()).toHaveLength(1);
    expect(prepared.map((p) => p.sql)).toEqual([
      "SELECT * FROM foodbankchange_full WHERE id = ?",
      "SELECT uuid, slug, name FROM foodbank WHERE id = ?",
    ]);
  });

  it("logs the message name FCM assigned, which is the only receipt this channel gets", async () => {
    fcmReply = () => okFcm("projects/givefood-test/messages/0:1757332800000000%deadbeef");

    await notify();

    expect(consoleLog).toHaveBeenCalledWith(
      `notify-need-firebase: sent need ${NEED_ID} to topic foodbank-${SALISBURY_UUID}: projects/givefood-test/messages/0:1757332800000000%deadbeef`,
    );
    expect(consoleError).not.toHaveBeenCalled();
  });

  it("says (no name) when the success response carries no message name", async () => {
    fcmReply = () => new Response("{}", { status: 200 });

    await notify();

    expect(consoleLog).toHaveBeenCalledWith(
      `notify-need-firebase: sent need ${NEED_ID} to topic foodbank-${SALISBURY_UUID}: (no name)`,
    );
  });
});

// ===========================================================================
// When FCM fails
// ===========================================================================

describe("when FCM refuses the message", () => {
  // The log carries the status, the need, the topic AND Google's body --
  // all four, because this line is the entire diagnosis available for a
  // notification that nobody received and nothing recorded.
  it("logs the status, the need, the topic and Google's own error body", async () => {
    fcmReply = () =>
      new Response(JSON.stringify({ error: { code: 404, status: "NOT_FOUND", message: "Requested entity was not found." } }), {
        status: 404,
      });

    await expect(notify()).resolves.toBeUndefined();

    expect(consoleError).toHaveBeenCalledWith(
      `notify-need-firebase: FCM 404 for need ${NEED_ID} topic foodbank-${SALISBURY_UUID}: ` +
        '{"error":{"code":404,"status":"NOT_FOUND","message":"Requested entity was not found."}}',
    );
    // Crucially NOT logged as a success: the success line is what an
    // operator greps for, and a failure that also logged one would be
    // indistinguishable from a delivery.
    expect(consoleLog).not.toHaveBeenCalled();
  });

  it("logs and returns when FCM cannot be reached", async () => {
    fcmReply = () => {
      throw new TypeError("Network connection lost.");
    };

    await expect(notify()).resolves.toBeUndefined();

    expect(consoleError).toHaveBeenCalledWith(`notify-need-firebase: send failed for need ${NEED_ID}`, expect.any(TypeError));
    expect(consoleLog).not.toHaveBeenCalled();
  });

  // SUSPECT, pinned as-is. The response body is parsed INSIDE the try, after
  // the ok check has passed, so a 200 whose body is not JSON is reported as
  // "send failed" -- for a message FCM has already accepted and delivered.
  // Nothing re-sends it (the caller acks), so the consequence is a false
  // failure in the log rather than a duplicate notification, but an
  // operator chasing it is chasing a send that worked. Reported, not fixed.
  it("reports a successful send as failed when the 200 body is not JSON", async () => {
    fcmReply = () => new Response("OK", { status: 200 });

    await notify();

    expect(consoleError).toHaveBeenCalledWith(`notify-need-firebase: send failed for need ${NEED_ID}`, expect.any(Error));
    expect(consoleLog).not.toHaveBeenCalled();
  });

  // SUSPECT, pinned as-is, and the worst of the three because it lasts an
  // hour. A 401 means the token is dead -- revoked key, disabled service
  // account -- and nothing invalidates `cachedToken`, so every subsequent
  // message in the isolate presents the SAME dead token and fails
  // identically. No retry, no DLQ, no row: an hour of app notifications
  // vanish leaving only console.error behind. Reported, not fixed.
  it("keeps presenting a token FCM has just rejected as unauthorised", async () => {
    fcmReply = () => new Response(JSON.stringify({ error: { code: 401, status: "UNAUTHENTICATED" } }), { status: 401 });

    await notify(NEED_ID);
    await notify(DECOY_NEED_ID);

    expect(tokenCalls()).toHaveLength(1);
    expect(fcmCalls().map((c) => c.headers.Authorization)).toEqual([`Bearer ${ACCESS_TOKEN}`, `Bearer ${ACCESS_TOKEN}`]);
    expect(consoleError).toHaveBeenCalledTimes(2);
  });
});

// ===========================================================================
// What it never does
// ===========================================================================

describe("the database is only ever read", () => {
  // The `notified` stamp is the PRODUCER's business (routes/admin/needs.ts
  // writes it before enqueuing all four channels). If this consumer ever
  // started writing, an at-least-once redelivery would rewrite it, and a
  // failed send would leave a need looking notified. Reading the row back
  // is the assertion; a green status from the handler is not.
  it("leaves the need row byte-identical after a successful send", async () => {
    const before = needRow(NEED_ID);

    await notify();

    expect(needRow(NEED_ID)).toEqual(before);
    expect(before.notified).toBeNull();
  });

  // Every statement, not just the ones with obvious side effects: a shared
  // packages/db helper that grew a write would land here silently.
  it("runs nothing but SELECTs", async () => {
    await notify();

    for (const statement of prepared) expect(statement.sql.trimStart().slice(0, 6).toUpperCase()).toBe("SELECT");
  });
});

describe("at-least-once delivery -- Cloudflare Queues can deliver the same tick twice", () => {
  // NOT IDEMPOTENT, BY DESIGN, and the design is stated in the module's own
  // header: "A notification is worth sending once, at the moment the
  // reviewer pressed the button". There is no dedup key and no stamp, so a
  // redelivered message really does buzz every subscribed phone a second
  // time. Pinned so that the absence of a guard is a decision on record
  // rather than an oversight -- and so that anyone adding one has to change
  // this test deliberately.
  it("sends again on a redelivered message, with no dedup and no stamp", async () => {
    await notify();
    await notify();

    expect(fcmCalls()).toHaveLength(2);
    expect(fcmCalls()[0]!.body).toBe(fcmCalls()[1]!.body);
    // One mint, two sends: the cache absorbs the duplicate's cost.
    expect(tokenCalls()).toHaveLength(1);
    expect(needRow(NEED_ID).notified).toBeNull();
  });
});

// ===========================================================================
// Through the real consumer
// ===========================================================================

// The ack/retry decision is not made in needFirebase.ts -- it is made in
// queues/jobs.ts, which acks on return and retries on throw. Since every
// failure above returns, EVERY firebase failure is acked. Asserting that
// through the REAL handleJobsQueue rather than by reasoning about it is the
// point: the "jobs" queue is configured max_retries 3 with a jobs-dlq
// (workers/jobs/wrangler.jsonc:149-152), so "acks" means a broken Firebase
// credential produces an EMPTY dead-letter queue while every app
// notification stops. That is the invisible-failure shape this whole file
// is about, and it is deliberate: Django's send_firebase_notification
// swallows its exceptions the same way.
describe("through the real jobs consumer -- what actually gets acked", () => {
  interface FakeMessage {
    body: unknown;
    ack: () => void;
    retry: () => void;
  }

  function fakeBatch(bodies: unknown[]) {
    const acked: number[] = [];
    const retried: number[] = [];
    const messages: FakeMessage[] = bodies.map((body, index) => ({
      body,
      ack: () => void acked.push(index),
      retry: () => void retried.push(index),
    }));
    const batch = { queue: "jobs", messages } as unknown as Parameters<typeof handleJobsQueue>[0];
    return { batch, acked, retried };
  }

  it("routes a notify-need-firebase message to this handler and acks it", async () => {
    const { batch, acked, retried } = fakeBatch([message()]);

    await handleJobsQueue(batch, buildEnv());

    expect(fcmCalls()).toHaveLength(1);
    expect(acked).toEqual([0]);
    expect(retried).toEqual([]);
  });

  it("acks a message whose FCM send was refused, so nothing ever reaches jobs-dlq", async () => {
    fcmReply = () => new Response("no", { status: 500 });
    const { batch, acked, retried } = fakeBatch([message()]);

    await handleJobsQueue(batch, buildEnv());

    expect(acked).toEqual([0]);
    expect(retried).toEqual([]);
    expect(consoleError).toHaveBeenCalledWith(expect.stringContaining("notify-need-firebase: FCM 500"));
  });

  it("acks a message for a need that no longer exists", async () => {
    const { batch, acked, retried } = fakeBatch([message(4242)]);

    await handleJobsQueue(batch, buildEnv());

    expect(acked).toEqual([0]);
    expect(retried).toEqual([]);
  });

  it("acks a message whose credential is missing, leaving only the warning", async () => {
    const { batch, acked, retried } = fakeBatch([message()]);

    await handleJobsQueue(batch, buildEnv({ FIREBASE_SERVICE_ACCOUNT: undefined }));

    expect(acked).toEqual([0]);
    expect(retried).toEqual([]);
    expect(consoleWarn).toHaveBeenCalledTimes(1);
  });

  // THE MALFORMED MESSAGE. queues/jobs.ts:70 casts the body without
  // validating it, so a message with no needId reaches getNeedById with
  // `undefined` and the DRIVER rejects the bind -- there is no guard in
  // this handler for it. That throws out of the handler, which is the one
  // path that does NOT ack: three retries and then jobs-dlq, which is the
  // right destination for a message no amount of retrying will fix.
  //
  // The error object here is node:sqlite's TypeError, because that is what
  // this harness's session is built on; D1 raises its own type error for an
  // undefined bind. Not verified against a live D1 -- what is asserted, and
  // all that matters to the queue, is that the handler does not swallow it.
  it("lets a message with no needId throw, so it retries rather than being acked", async () => {
    const { batch, acked, retried } = fakeBatch([{ type: "notify-need-firebase" }]);

    await handleJobsQueue(batch, buildEnv());

    expect(retried).toEqual([0]);
    expect(acked).toEqual([]);
    expect(calls).toEqual([]);
  });

  // SUSPECT, pinned as-is: the ONE credential shape that does not ack.
  // parseServiceAccount's try wraps only the JSON.parse, so a credential
  // whose text is `null` parses cleanly to null and is dereferenced on the
  // very next line -- a TypeError out of the handler, three retries, and a
  // jobs-dlq entry, where every other broken credential in this file warns
  // or logs once and acks. Nobody sets a secret to "null" deliberately; what
  // this pins is that the module's stated contract ("a missing credential is
  // a warning and a return, not an error") has exactly one hole in it, and
  // that the hole is in the direction of a retry rather than a silent ack.
  // Reported, not fixed.
  it("retries rather than acks when the credential parses to null", async () => {
    const { batch, acked, retried } = fakeBatch([message()]);

    await handleJobsQueue(batch, buildEnv({ FIREBASE_SERVICE_ACCOUNT: "null" }));

    expect(retried).toEqual([0]);
    expect(acked).toEqual([]);
    expect(consoleError).toHaveBeenCalledWith(
      'givefood2-jobs: "jobs" message failed',
      { type: "notify-need-firebase", needId: NEED_ID },
      expect.any(TypeError),
    );
    // Not even the database was touched, so the retries are free apart from
    // the queue's own delivery.
    expect(calls).toEqual([]);
    expect(prepared).toEqual([]);
  });

  // A batch is up to ten messages (wrangler.jsonc:149) and the notify fan-out
  // sends four at a time, so several firebase messages in one batch is the
  // normal case rather than the exotic one. One failing message must not
  // cost the others their send -- and the cached token means the batch
  // costs one exchange, not one per message.
  it("keeps sending the rest of the batch when one message's need is gone", async () => {
    const { batch, acked, retried } = fakeBatch([message(4242), message(NEED_ID), message(DECOY_NEED_ID)]);

    await handleJobsQueue(batch, buildEnv());

    expect(acked).toEqual([0, 1, 2]);
    expect(retried).toEqual([]);
    expect(tokenCalls()).toHaveLength(1);
    expect(fcmCalls().map((c) => (JSON.parse(c.body) as { message: { topic: string } }).message.topic)).toEqual([
      `foodbank-${SALISBURY_UUID}`,
      `foodbank-${DEVIZES_UUID}`,
    ]);
  });
});
