import { describe, expect, it } from "vitest";
import { isoWeekNumber, parseD1Timestamp, weekKey } from "./isoWeek";

// These three helpers together produce the x-axis of two public dashboards
// ("Items requested by UK food banks per week", and its year-by-year grid)
// plus the admin subscriber-growth chart. Everything they get wrong shows up
// as a *plausible-looking* number on a chart rather than as an error, so the
// tests below pin the arithmetic against a known-good oracle -- Python's
// datetime.date.isocalendar() -- and against the two ticket numbers the
// module comments cite.

// Convenience: the dashboards only ever hand these helpers UTC instants.
const utc = (iso: string) => new Date(iso);

// An INDEPENDENT ISO-8601 week number, used as the oracle for the sweep test
// below. This is deliberately not the same algorithm as the module: it uses
// the ordinal-date formula from the standard -- week = (dayOfYear - isoWeekday
// + 10) / 7, with the under/overflow rules and the 52-or-53 long-year test --
// where isoWeek.ts hops to the nearest Thursday and measures against the
// first Thursday of January. It also derives the weekday by counting days
// from the epoch (1970-01-01 was a Thursday) rather than asking Date, so it
// shares no arithmetic at all with the code under test. Comparing the two is
// therefore a real cross-check, not the implementation re-run against itself.
//
// Verified before use: this function agrees with CPython's
// datetime.date(...).isocalendar()[1] on all 7,670 days of 2015-2035.
// Howard Hinnant's days-from-civil: pure integer arithmetic, no Date at all.
const daysFromEpoch = (year: number, month: number, day: number) => {
  const y = month <= 2 ? year - 1 : year;
  const era = Math.floor((y >= 0 ? y : y - 399) / 400);
  const yearOfEra = y - era * 400;
  const dayOfYearShifted = Math.floor((153 * (month + (month > 2 ? -3 : 9)) + 2) / 5) + day - 1;
  const dayOfEra =
    yearOfEra * 365 + Math.floor(yearOfEra / 4) - Math.floor(yearOfEra / 100) + dayOfYearShifted;
  return era * 146097 + dayOfEra - 719468;
};
const dayOfYear = (year: number, month: number, day: number) =>
  daysFromEpoch(year, month, day) - daysFromEpoch(year, 1, 1) + 1;
// Jan 1's ISO weekday, per the standard's "p(y)" helper.
const p = (year: number) =>
  (((year + Math.floor(year / 4) - Math.floor(year / 100) + Math.floor(year / 400)) % 7) + 7) % 7;
const weeksInIsoYear = (year: number) => 52 + (p(year) === 4 || p(year - 1) === 3 ? 1 : 0);
function isoWeekOracle(year: number, month: number, day: number): { isoYear: number; week: number } {
  const isoWeekday = ((((daysFromEpoch(year, month, day) + 3) % 7) + 7) % 7) + 1; // Mon=1..Sun=7
  const week = Math.floor((dayOfYear(year, month, day) - isoWeekday + 10) / 7);
  if (week < 1) return { isoYear: year - 1, week: weeksInIsoYear(year - 1) };
  if (week > weeksInIsoYear(year)) return { isoYear: year + 1, week: 1 };
  return { isoYear: year, week };
}

// Node re-reads process.env.TZ when it is assigned, so this genuinely moves
// the process's local zone for the duration of the callback. Restored in a
// finally, because leaking TZ would unmoor every test after this one --
// vitest.config.mts pins TZ=UTC for the whole suite on purpose.
// (Same technique as workers/jobs/src/articles/feedParser.test.ts:1043.)
const inTimeZone = (timeZone: string, fn: () => void) => {
  const original = process.env.TZ;
  try {
    process.env.TZ = timeZone;
    fn();
  } finally {
    // `process.env.TZ = undefined` assigns the STRING "undefined", which Node
    // treats as an unknown zone and quietly falls back to -- leaving every
    // later test in this file running somewhere unintended, including the
    // parseD1Timestamp block whose whole point is that it does not depend on
    // the zone. vitest.config.mts:24 pins TZ=UTC so `original` is always set
    // today; the delete branch is here so that removing that pin fails
    // loudly rather than poisoning the rest of the file.
    if (original === undefined) delete process.env.TZ;
    else process.env.TZ = original;
  }
};

describe("isoWeekNumber", () => {
  // The whole point of this function is to reproduce Python's
  // `date.isocalendar()[1]`, because SQLite has nothing equivalent
  // (adminStats.ts:250-257) and the port must not renumber existing
  // dashboard buckets. Every expectation in this block was generated by
  // running datetime.date(...).isocalendar() against CPython, not by
  // reading this implementation back to itself.
  it("agrees with Python's date.isocalendar()[1] on ordinary mid-year dates", () => {
    expect(isoWeekNumber(utc("2026-09-05T00:00:00Z"))).toBe(36);
    expect(isoWeekNumber(utc("2020-01-01T00:00:00Z"))).toBe(1);
    expect(isoWeekNumber(utc("2023-06-15T00:00:00Z"))).toBe(24);
    expect(isoWeekNumber(utc("2022-03-01T00:00:00Z"))).toBe(9);
  });

  // ISO 8601 week 1 is the week containing the first Thursday of January,
  // which is why the implementation walks to "nearest Thursday" instead of
  // dividing the day-of-year by seven. These four dates are the cases where
  // a naive day-of-year/7 gets it wrong, and where a wrong answer would
  // silently move a whole week's item count into the neighbouring bar.
  it("puts late-December dates into week 1 when they belong to the next ISO year", () => {
    // 2019-12-30 is a Monday and is ISO 2020-W01-1 in Python.
    expect(isoWeekNumber(utc("2019-12-30T00:00:00Z"))).toBe(1);
    expect(isoWeekNumber(utc("2019-12-31T00:00:00Z"))).toBe(1);
    // 2024-12-30 is likewise ISO 2025-W01-1.
    expect(isoWeekNumber(utc("2024-12-30T00:00:00Z"))).toBe(1);
    // The Sunday immediately before is still week 52 of the old year.
    expect(isoWeekNumber(utc("2019-12-29T00:00:00Z"))).toBe(52);
  });

  it("puts early-January dates into week 52/53 when they belong to the previous ISO year", () => {
    // 2021-01-01 is a Friday: ISO 2020-W53-5 in Python.
    expect(isoWeekNumber(utc("2021-01-01T00:00:00Z"))).toBe(53);
    expect(isoWeekNumber(utc("2021-01-03T00:00:00Z"))).toBe(53);
    // The following Monday starts ISO 2021-W01.
    expect(isoWeekNumber(utc("2021-01-04T00:00:00Z"))).toBe(1);
    // 2016-01-01 is ISO 2015-W53-5.
    expect(isoWeekNumber(utc("2016-01-01T00:00:00Z"))).toBe(53);
  });

  // Only some years have a week 53 (2020 and 2026 do; 2021 does not), and
  // weeklyItemcountYear.ts renders a fixed 1..53 grid off the back of that
  // (MAX_WEEK = 53, `weeks = range(1,54)` in views.py:56). If this returned
  // 53 for a 52-week year, the grid would gain a phantom populated row; if
  // it returned 52 for 2020, a real week's needs would be merged into the
  // wrong bucket. The exhaustive version of this claim -- which ISO years
  // may contain a 53 AT ALL -- is asserted in the sweep test below.
  it("reaches week 53 only in long ISO years", () => {
    expect(isoWeekNumber(utc("2020-12-28T00:00:00Z"))).toBe(53); // 2020 is a 53-week year
    expect(isoWeekNumber(utc("2026-12-31T00:00:00Z"))).toBe(53); // so is 2026
    expect(isoWeekNumber(utc("2021-12-27T00:00:00Z"))).toBe(52); // 2021 tops out at 52
    expect(isoWeekNumber(utc("2019-12-29T00:00:00Z"))).toBe(52);
  });

  // ISO weeks run Monday to Sunday. Django's isocalendar() does too, and
  // SQLite's strftime('%W') famously does not -- which is the reason this
  // bucketing happens in JS at all.
  //
  // Every day of 2015-2035 is checked against the independent ordinal-date
  // oracle above, so this is a differential test and not a restatement of
  // the implementation. The structural invariants are asserted alongside it
  // because they are what a reader of the dashboards relies on, and because
  // a mutant can be wrong in a way a spot check misses: an off-by-one in the
  // Thursday hop, a Sunday-based weekday, or a week that jumps 40 -> 42
  // without ever leaving 1..53.
  it("matches an independent ISO-8601 oracle every day from 2015 to 2035", () => {
    const DAY_MS = 86_400_000;
    const disagreements: string[] = [];
    const outOfRange: string[] = [];
    const midWeekChanges: string[] = [];
    const badSteps: string[] = [];
    const longIsoYears = new Set<number>();
    let previous: number | null = null;

    for (let t = Date.UTC(2015, 0, 1); t < Date.UTC(2036, 0, 1); t += DAY_MS) {
      const day = new Date(t);
      const week = isoWeekNumber(day);
      const expected = isoWeekOracle(
        day.getUTCFullYear(),
        day.getUTCMonth() + 1,
        day.getUTCDate(),
      );
      const iso = day.toISOString().slice(0, 10);

      if (week !== expected.week) disagreements.push(`${iso}: ${week} != ${expected.week}`);
      if (!Number.isInteger(week) || week < 1 || week > 53) outOfRange.push(iso);
      if (week === 53) longIsoYears.add(expected.isoYear);
      if (previous !== null && week !== previous) {
        // getUTCDay(): 1 === Monday. A week number may only ever change on a
        // Monday, and when it does it either advances by one or restarts the
        // ISO year at 1. Nothing else is a legal transition.
        if (day.getUTCDay() !== 1) midWeekChanges.push(iso);
        else if (week !== previous + 1 && week !== 1) badSteps.push(`${iso}: ${previous} -> ${week}`);
      }
      previous = week;
    }

    expect(disagreements).toEqual([]);
    expect(outOfRange).toEqual([]);
    expect(midWeekChanges).toEqual([]);
    expect(badSteps).toEqual([]);
    // The complete set of ISO years in that span that HAVE a week 53. Any
    // other year showing a 53 would put a phantom row in the year grid.
    //
    // Numeric comparator deliberately: Array.prototype.sort() with no
    // argument compares STRINGS, which only happens to give year order while
    // every value is four digits. It would silently stop agreeing the moment
    // this sweep were widened past 9999 or before 1000, and a test whose
    // ordering is correct by luck is a test that fails for the wrong reason.
    expect([...longIsoYears].sort((a, b) => a - b)).toEqual([2015, 2020, 2026, 2032]);
  });

  // All seven days of one ISO week must land in the same bar. This is the
  // property a "count needs per week" chart is actually made of.
  it("gives every day of a single ISO week the same number", () => {
    // 2026-08-31 (Mon) .. 2026-09-06 (Sun) is ISO 2026-W36.
    const week36 = [
      "2026-08-31",
      "2026-09-01",
      "2026-09-02",
      "2026-09-03",
      "2026-09-04",
      "2026-09-05",
      "2026-09-06",
    ].map((d) => isoWeekNumber(utc(`${d}T12:00:00Z`)));
    expect(week36).toEqual([36, 36, 36, 36, 36, 36, 36]);
    expect(isoWeekNumber(utc("2026-09-07T00:00:00Z"))).toBe(37); // next Monday
  });

  // A need created at 23:59 must land in the same bar as one created at
  // 00:00 -- that is the observable property, and it is what this pins.
  //
  // Stated honestly, because the obvious comment here would over-claim: the
  // midnight rebuild and the Math.round() are JOINTLY redundant, not each
  // load-bearing. Both endpoints of the subtraction are Thursdays at UTC
  // midnight, so the division is always an exact integer and floor/round
  // cannot differ; and dropping the rebuild leaves a remainder below 1/7 of
  // a week, which Math.round() then absorbs. Removing EITHER one alone is
  // undetectable from outside (checked over 1.2M instants, 1960-2100), so no
  // test in this file can catch it, and pretending otherwise would be worse
  // than saying so. Removing BOTH is what breaks -- keep them together.
  it("ignores the time of day, including across an ISO-year boundary", () => {
    expect(isoWeekNumber(utc("2026-09-05T00:00:00.000Z"))).toBe(36);
    expect(isoWeekNumber(utc("2026-09-05T23:59:59.999Z"))).toBe(36);
    // The last millisecond of ISO 2019-W52 and the first of ISO 2020-W01.
    expect(isoWeekNumber(utc("2019-12-29T23:59:59.999Z"))).toBe(52);
    expect(isoWeekNumber(utc("2019-12-30T00:00:00.000Z"))).toBe(1);
  });

  // THE HOLE EVERY OTHER TEST IN THIS FILE LEAVES OPEN. The module reads
  // every field with getUTC*, but vitest.config.mts pins TZ=UTC, so an
  // implementation that used getFullYear()/getMonth()/getDate() instead
  // would pass every single assertion above. Workers run UTC today; a
  // developer running one of these dashboards locally, or any future move to
  // a runtime that is not UTC, would then silently shift needs created near
  // midnight into the neighbouring week. So the zone is moved for real here
  // and the answers must not budge.
  //
  // If this test ever fails on the FIRST assertion in a block, the zone
  // failed to load (a Node build without full ICU tzdata) -- that is an
  // environment problem, not a regression in isoWeek.ts.
  it("reads the date in UTC, so the answer is TZ-independent and not merely TZ-pinned", () => {
    // Sunday 2026-09-06 23:30Z is ISO 2026-W36. In Kiritimati (UTC+14) the
    // local date is already Monday the 7th, which is W37.
    const lateSunday = utc("2026-09-06T23:30:00Z");
    inTimeZone("Pacific/Kiritimati", () => {
      expect(lateSunday.getDate()).toBe(7); // the zone really did shift local time
      expect(isoWeekNumber(lateSunday)).toBe(36);
    });

    // Monday 2026-09-07 00:30Z is W37. In Midway (UTC-11) it is still
    // Sunday the 6th locally, which is W36.
    const earlyMonday = utc("2026-09-07T00:30:00Z");
    inTimeZone("Pacific/Midway", () => {
      expect(earlyMonday.getDate()).toBe(6);
      expect(isoWeekNumber(earlyMonday)).toBe(37);
    });

    // And unchanged once the zone is restored, so the two blocks above are
    // statements about the module rather than about the environment.
    expect(isoWeekNumber(lateSunday)).toBe(36);
    expect(isoWeekNumber(earlyMonday)).toBe(37);
    // Those two lines would pass just as happily if inTimeZone had failed to
    // put the zone back, because the module's answers do not depend on it --
    // which is exactly why the restore needs checking directly. A leaked TZ
    // here re-points every test below, and getTimezoneOffset() is 0 in UTC
    // and nowhere near 0 in either zone used above. Fresh Dates on purpose,
    // so a failure here means the zone leaked and nothing else.
    expect(utc("2026-09-06T23:30:00Z").getTimezoneOffset()).toBe(0);
    expect(utc("2026-09-06T23:30:00Z").getDate()).toBe(6); // not Kiritimati's Monday
    expect(utc("2026-09-07T00:30:00Z").getDate()).toBe(7); // not Midway's Sunday
  });

  // The zone pair above moves the INPUT across a local midnight, which is
  // what catches a getUTCDay()/getUTCFullYear() slip on lines 11-13. It
  // cannot catch one on lines 14-16, where the year's first-Thursday ANCHOR
  // is built from Date.UTC(year, 0, 4) and read back with getUTCDay(), for
  // two separate reasons:
  //
  //   * only a zone WEST of UTC pushes 4 January 00:00Z onto the previous
  //     local day at all, so Kiritimati (UTC+14) sees no difference; and
  //   * a one-day anchor slip is normally swallowed by the Math.round(),
  //     since two Thursdays are a whole number of weeks apart and 1/7 of a
  //     week rounds away. It only becomes visible where the weekday index
  //     WRAPS: with 4 January on a Monday (2016, 2021, 2027...) a local
  //     Sunday reading turns dayNum 0 into 6 and moves the anchor six days,
  //     which is 6/7 of a week and rounds to a whole one.
  //
  // So these are the two dates on which reading the anchor in local time
  // stops being invisible -- and the symptom would be an entire year of the
  // weekly chart shifted along by one bar.
  it("builds the first-Thursday anchor in UTC too, not only the input date", () => {
    inTimeZone("Pacific/Midway", () => {
      // Proof the zone loaded: 4 Jan 2021 00:00Z is 3 Jan locally in Midway.
      expect(new Date(Date.UTC(2021, 0, 4)).getDate()).toBe(3);
      // Python: date(2021, 6, 15).isocalendar() == (2021, 24, 2). ISO 2021
      // began on Monday 4 January, so the anchor's weekday index is 0 and
      // this is the wrap case above.
      expect(isoWeekNumber(utc("2021-06-15T00:00:00Z"))).toBe(24);
      // 1 Jan 2015 is itself a Thursday, so the working copy never leaves
      // 1 January and a local-time read of ITS year would look up 2014's
      // anchor -- returning 53 (of the wrong year) instead of 1.
      expect(isoWeekNumber(utc("2015-01-01T00:00:00Z"))).toBe(1);
    });
    // Identical answers with no override, so the block above is a statement
    // about UTC-reading rather than about Midway.
    expect(isoWeekNumber(utc("2021-06-15T00:00:00Z"))).toBe(24);
    expect(isoWeekNumber(utc("2015-01-01T00:00:00Z"))).toBe(1);
  });

  // Line 11 rebuilds the argument into a FRESH Date before line 13 walks it
  // to the nearest Thursday with setUTCDate(). That copy is load-bearing and
  // easy to lose: `const d = date` reads as a harmless simplification, still
  // returns the right week number, and would additionally move the caller's
  // own Date by up to three days as a side effect.
  //
  // No other test here would notice -- they all hand over a throwaway Date
  // and never look at it again -- but adminSubscriberGraph (stats.ts:259)
  // and both weekly dashboards would then be holding a silently rewritten
  // `created` after bucketing it, and weekKey() itself only escapes because
  // template literals happen to evaluate the year half first.
  it("does not mutate the Date it is handed", () => {
    // A Sunday: dayNum 6, the largest backwards hop (-3 days).
    const sunday = utc("2026-09-06T23:30:00Z");
    expect(isoWeekNumber(sunday)).toBe(36);
    expect(sunday.toISOString()).toBe("2026-09-06T23:30:00.000Z");

    // A Monday: dayNum 0, the largest forwards hop (+3 days).
    const monday = utc("2026-09-07T00:30:00Z");
    expect(isoWeekNumber(monday)).toBe(37);
    expect(monday.toISOString()).toBe("2026-09-07T00:30:00.000Z");

    // weekKey() inherits the same guarantee, and the dashboards' template
    // context still needs `created` intact after bucketing.
    const created = utc("2020-12-31T23:59:59.999Z");
    expect(weekKey(created)).toBe("2020-53");
    expect(created.toISOString()).toBe("2020-12-31T23:59:59.999Z");
  });

  // Not a nicety: weekKey()'s null guard exists precisely because this
  // returns NaN rather than throwing on an Invalid Date. If this ever
  // started throwing, the guard would stop being a guard and a single bad
  // D1 row would 500 the whole dashboard instead of being skipped.
  it("returns NaN for an Invalid Date rather than throwing", () => {
    expect(() => isoWeekNumber(new Date(Number.NaN))).not.toThrow();
    expect(isoWeekNumber(new Date(Number.NaN))).toBeNaN();
    // The other way a bad D1 row reaches here: new Date("...") of text that
    // does not parse, which is what parseD1Timestamp() hands back.
    expect(isoWeekNumber(new Date("not a timestamp"))).toBeNaN();

    // Where the tolerance ends, stated so the guard's scope is not overread.
    // An Invalid DATE is survivable; a non-Date is not, because line 11 goes
    // straight to .getUTCFullYear() with no check. Pinned as behaviour, not
    // endorsed -- see weekKey's matching test below for why a NULL `created`
    // column makes this reachable in principle.
    expect(() => isoWeekNumber(null as unknown as Date)).toThrow(TypeError);
    expect(() => isoWeekNumber(undefined as unknown as Date)).toThrow(TypeError);
  });
});

describe("weekKey", () => {
  // Django: `week_key = "%s-%s" % (year, week_number)` (gfdash/views.py:35).
  it("renders Django's \"%s-%s\" % (year, week) key", () => {
    expect(weekKey(utc("2026-09-05T19:28:08Z"))).toBe("2026-36");
    expect(weekKey(utc("2023-06-15T00:00:00Z"))).toBe("2023-24");
  });

  // The week number is NOT zero-padded, because Python's %s of an int is
  // not. weeklyItemcountYear.ts:59 looks the buckets back up with
  // `${year}-${week}` built from a plain loop counter, so a "tidy" padding
  // to "2020-01" here would make every cell of the 53x7 year grid read zero
  // while still looking like well-formed output.
  it("does not zero-pad the week number", () => {
    expect(weekKey(utc("2020-01-01T00:00:00Z"))).toBe("2020-1");
    expect(weekKey(utc("2020-03-05T00:00:00Z"))).toBe("2020-10");

    // Consequence worth stating out loud -- and worth deriving from real
    // keys rather than two hand-typed strings, so that this fails if the
    // padding is ever added: these keys do NOT sort lexicographically into
    // week order. Both dashboards rely on Map insertion order (rows arrive
    // created-ascending) or on an explicit 1..53 loop -- never on sorting
    // the keys. Zero-padding would make the sort below a no-op.
    const chronological = ["2020-02-24", "2020-03-02"].map((d) => weekKey(utc(`${d}T00:00:00Z`)));
    expect(chronological).toEqual(["2020-9", "2020-10"]);
    expect([...chronological].sort()).toEqual(["2020-10", "2020-9"]);
  });

  // THE DOCUMENTED DIVERGENCE, reproduced on purpose. Django glues
  // `created.year` (plain calendar year) to `created.isocalendar()[1]` (ISO
  // week), which are not from the same calendar system near 1 January. The
  // module comment says this quirk is kept verbatim rather than "fixed"
  // into isocalendar()[0]; these two assertions are what a fix would break.
  it("glues the CALENDAR year to the ISO week, exactly as Django does", () => {
    // ISO says 2020-W53, Django says 2021 -- and so does this.
    expect(weekKey(utc("2021-01-01T00:00:00Z"))).toBe("2021-53");
    // ISO says 2020-W01, Django says 2019.
    expect(weekKey(utc("2019-12-30T00:00:00Z"))).toBe("2019-1");
    // Spelled out against the independent oracle so the divergence is
    // asserted as a difference, not just as a literal: the ISO year of
    // 2019-12-30 really is 2020, and the key really does say 2019.
    expect(isoWeekOracle(2019, 12, 30)).toEqual({ isoYear: 2020, week: 1 });
    expect(isoWeekOracle(2021, 1, 1)).toEqual({ isoYear: 2020, week: 53 });
  });

  // Those are four hand-picked dates. This is the same claim -- Django's
  // `"%s-%s" % (need.created.year, need.created.isocalendar()[1])` -- made
  // for every one of the 7,670 days from 2015 to 2035, built from the
  // independent oracle rather than from this module, so a port that is right
  // on the samples and wrong between them cannot hide. Note the year half is
  // taken from the DATE, not from `oracle.isoYear`: that is the quirk, and
  // this sweep is the strongest statement in the file that it is kept.
  //
  // The second half is the shape contract weeklyItemcountYear.ts:59 depends
  // on. That view regenerates keys itself, with `${year}-${week}` over year
  // 2020..current and a plain `for (week = 1; week <= 53; week++)` loop
  // (MAX_WEEK = 53, views.py:56's `range(1,54)`). Any key this function
  // emits that the loop cannot reproduce character for character -- padded
  // to "2020-01", a week 0 or 54, or an ISO year in the first half -- is a
  // bucket of real needs that renders as an empty cell in the 53-row grid
  // while the totals underneath still count them.
  it("emits Django's exact key every day from 2015 to 2035, in a shape the year grid can look up", () => {
    const DAY_MS = 86_400_000;
    // Exactly what the year grid's own loop can produce: four digits, a
    // hyphen, and an unpadded 1..53. A leading zero on the week fails here.
    const GRID_KEY = /^(\d{4})-([1-9]|[1-4]\d|5[0-3])$/;
    const wrongKey: string[] = [];
    const unlookupable: string[] = [];
    const weeksSeen = new Set<number>();
    let dayCount = 0;

    for (let t = Date.UTC(2015, 0, 1); t < Date.UTC(2036, 0, 1); t += DAY_MS) {
      const day = new Date(t);
      const iso = day.toISOString().slice(0, 10);
      const key = weekKey(day);
      dayCount++;

      const oracle = isoWeekOracle(day.getUTCFullYear(), day.getUTCMonth() + 1, day.getUTCDate());
      const django = `${day.getUTCFullYear()}-${oracle.week}`; // views.py:35
      if (key !== django) wrongKey.push(`${iso}: ${key} != ${django}`);

      const match = GRID_KEY.exec(key ?? "");
      if (!match || Number(match[1]) !== day.getUTCFullYear()) unlookupable.push(`${iso}: ${key}`);
      else weeksSeen.add(Number(match[2]));
    }

    expect(wrongKey).toEqual([]);
    expect(unlookupable).toEqual([]);
    expect(dayCount).toBe(7670); // the sweep really ran; a stray `continue` would show here
    // Every row of the 1..53 grid is reachable from a real date in that span,
    // so MAX_WEEK is neither too small (a week with no row) nor a number the
    // keys never actually use.
    expect([...weeksSeen].sort((a, b) => a - b)).toEqual(
      Array.from({ length: 53 }, (_, i) => i + 1),
    );
  });

  // The quirk has two visible effects on the chart, and both are the
  // *current* behaviour of the Django site, so the port has to keep them.
  it("collapses two distinct ISO weeks of the same calendar year into one bucket", () => {
    // 2019-01-03 is ISO 2019-W01. 2019-12-30 is ISO 2020-W01. Different
    // weeks eleven months apart, one key: their item counts are summed
    // into a single bar.
    expect(weekKey(utc("2019-01-03T00:00:00Z"))).toBe("2019-1");
    expect(weekKey(utc("2019-12-30T00:00:00Z"))).toBe("2019-1");
    // Asserted, not just asserted-in-a-comment: the two dates really are
    // DIFFERENT ISO weeks. Without this the test would pass just as well
    // against an implementation that thought they were the same week, which
    // would make the shared bucket correct rather than a quirk.
    expect(isoWeekOracle(2019, 1, 3)).toEqual({ isoYear: 2019, week: 1 });
    expect(isoWeekOracle(2019, 12, 30)).toEqual({ isoYear: 2020, week: 1 });
  });

  it("splits one ISO week across two buckets at the new year", () => {
    // ISO 2020-W53 runs Mon 2020-12-28 to Sun 2021-01-03. The Monday-to-
    // Thursday half is keyed 2020-53 and the Friday-to-Sunday half 2021-53.
    expect(weekKey(utc("2020-12-28T00:00:00Z"))).toBe("2020-53");
    expect(weekKey(utc("2020-12-31T00:00:00Z"))).toBe("2020-53");
    expect(weekKey(utc("2021-01-01T00:00:00Z"))).toBe("2021-53");
    expect(weekKey(utc("2021-01-03T00:00:00Z"))).toBe("2021-53");
    // Likewise the converse of the test above: all four dates are ONE ISO
    // week, so the two keys are a genuine split and not two real weeks.
    for (const [y, m, d] of [
      [2020, 12, 28],
      [2020, 12, 31],
      [2021, 1, 1],
      [2021, 1, 3],
    ] as const) {
      expect(isoWeekOracle(y, m, d), `${y}-${m}-${d}`).toEqual({ isoYear: 2020, week: 53 });
    }
  });

  // The year half of the key has the same TZ exposure as the week half, and
  // it is the half Django takes from `created.year`. A getFullYear() here
  // would move a New Year's Eve need into the next year's bucket for anyone
  // east of UTC -- and under the suite's pinned TZ=UTC nothing else in this
  // file would notice.
  it("takes the calendar year from UTC too, not from the local zone", () => {
    const newYearsEve = utc("2020-12-31T23:30:00Z");
    inTimeZone("Pacific/Kiritimati", () => {
      expect(newYearsEve.getFullYear()).toBe(2021); // local year has rolled over
      expect(weekKey(newYearsEve)).toBe("2020-53");
    });
    const newYearsDay = utc("2021-01-01T00:30:00Z");
    inTimeZone("Pacific/Midway", () => {
      expect(newYearsDay.getFullYear()).toBe(2020); // local year has not yet
      expect(weekKey(newYearsDay)).toBe("2021-53");
    });
  });

  // Ticket #7: a screenshot of a "NaN-NaN" bucket sitting at the end of the
  // public weekly chart. The second assertion is the bug itself, kept here
  // so the guard can never be deleted as "obviously unreachable" -- it is
  // exactly what the template renders if weekKey stops checking.
  it("returns null for an Invalid Date instead of the string \"NaN-NaN\" (ticket #7)", () => {
    const invalid = new Date(Number.NaN);
    expect(weekKey(invalid)).toBeNull();
    expect(`${invalid.getUTCFullYear()}-${isoWeekNumber(invalid)}`).toBe("NaN-NaN");
  });

  // WHAT THE NULL RETURN IS *NOT*. The guard tests the TIME VALUE of a Date
  // for NaN; it does not test that it was handed a Date. Callers pass
  // `weekKey(parseD1Timestamp(row.created))` and `row.created` is typed
  // `string` (packages/db/src/dashboards.ts:25), but that is a compile-time
  // promise about a nullable TEXT column -- the same gap parseD1Timestamp's
  // own test below records. Both dashboards catch nothing, so a wrong-typed
  // value 500s the page rather than skipping the row, which is the exact
  // failure the null-return design exists to avoid.
  //
  // Pinned as current behaviour. If a guard is ever added, change this test
  // on purpose.
  it("THROWS rather than returning null when handed something that is not a Date", () => {
    expect(() => weekKey(null as unknown as Date)).toThrow(TypeError);
    expect(() => weekKey(undefined as unknown as Date)).toThrow(TypeError);
    // The two plausible mistakes at a call site: passing the raw column
    // through, or passing epoch milliseconds instead of a Date.
    expect(() => weekKey("2026-09-05 19:28:08.853000" as unknown as Date)).toThrow(TypeError);
    expect(() => weekKey(1_788_636_488_000 as unknown as Date)).toThrow(TypeError);
  });

  it("returns null for the unparseable-timestamp path the callers actually hit", () => {
    // Both weekly dashboards call weekKey(parseD1Timestamp(row.created)),
    // and skip the row on null (weeklyItemcount.ts:33-35). A row whose
    // `created` is empty or corrupt costs that row, not the chart.
    expect(weekKey(parseD1Timestamp(""))).toBeNull();
    expect(weekKey(parseD1Timestamp("not a timestamp"))).toBeNull();
  });

  it("never returns null for a valid date, however far from today", () => {
    // The guard is narrowly about NaN. Ancient and far-future instants are
    // real keys, not skipped rows -- FoodbankChange rows predate the port
    // and the dashboards are cached for a day, so "now" is never assumed.
    expect(weekKey(utc("1970-01-01T00:00:00Z"))).toBe("1970-1");
    expect(weekKey(utc("2099-06-01T00:00:00Z"))).toBe("2099-23");
    // Epoch zero and negative epoch: the subtraction inside isoWeekNumber
    // goes negative for anything before 1970-01-04, which is where a signed/
    // unsigned or truncating-division mistake would surface.
    expect(weekKey(new Date(0))).toBe("1970-1");
    expect(weekKey(new Date(-0))).toBe("1970-1");
    expect(weekKey(utc("1969-12-29T00:00:00Z"))).toBe("1969-1"); // ISO 1970-W01
    expect(weekKey(utc("1969-01-01T00:00:00Z"))).toBe("1969-1"); // and ISO 1969-W01
    expect(weekKey(utc("1900-01-01T00:00:00Z"))).toBe("1900-1");
  });

  // THE GUARD HAS A HOLE, recorded rather than fixed. weekKey() checks the
  // INPUT for NaN, but isoWeekNumber() can manufacture a fresh Invalid Date
  // of its own: it builds `Date.UTC(year, 0, 4)` for the year's first
  // Thursday, and for a date in the first months of the representable range
  // that anchor falls BELOW the -8.64e15 floor. The result is a non-null key
  // ending in "NaN" -- the exact shape ticket #7 was about -- returned for
  // an input the guard considers valid.
  //
  // Unreachable from D1 (no food bank need is dated 271821 BC) and so not
  // worth code churn, but pinned here so that the guard's true scope is
  // written down: it protects against NaN coming IN, not NaN arising inside.
  it("still produces a NaN-bearing key at the very start of the Date range", () => {
    const MIN_DATE_MS = -8_640_000_000_000_000;
    const MAX_DATE_MS = 8_640_000_000_000_000;

    expect(weekKey(new Date(MIN_DATE_MS))).toBe("-271821-NaN");
    // The top of the range is fine -- nothing there needs an out-of-range
    // anchor -- so this is specifically a bottom-of-range effect.
    expect(weekKey(new Date(MAX_DATE_MS))).toBe("275760-37");
    // One millisecond past either end IS an Invalid Date, and the guard does
    // its job there.
    expect(weekKey(new Date(MAX_DATE_MS + 1))).toBeNull();
    expect(weekKey(new Date(MIN_DATE_MS - 1))).toBeNull();
  });
});

describe("parseD1Timestamp", () => {
  // The shape the pg-to-D1 import wrote: Django's str(datetime), a space
  // separator and six fractional digits, with no timezone marker at all.
  // Reading it as anything but UTC would shift every need by the deploy
  // machine's offset.
  it("parses D1's stored \"YYYY-MM-DD HH:MM:SS.ffffff\" as UTC", () => {
    expect(parseD1Timestamp("2026-09-05 19:28:08.853000").toISOString()).toBe(
      "2026-09-05T19:28:08.853Z",
    );
    expect(parseD1Timestamp("2020-01-24 16:30:23.173000").toISOString()).toBe(
      "2020-01-24T16:30:23.173Z",
    );
  });

  // The "as UTC" half of that claim is the half TZ=UTC cannot prove. Without
  // the appended "Z", `new Date("2026-09-05T19:28:08.853")` is parsed as
  // LOCAL time by the spec, so this is the assertion that would catch the
  // append being dropped -- and it is invisible while the suite runs in UTC.
  it("appends the Z for real: the same text is the same instant in any zone", () => {
    const value = "2026-09-05 19:28:08.853000";
    inTimeZone("America/Los_Angeles", () => {
      // Proof the zone loaded: a local-time read of the same text is 7 hours
      // off in PDT, which is exactly the shift a missing "Z" would introduce.
      // Asserted as the exact instant rather than as `.not.toBe(UTC)`, which
      // would be satisfied by the zone loading as anything at all -- and a
      // zone that failed to load in the direction of, say, +00:30 would leave
      // this block claiming a proof it had not made.
      expect(new Date("2026-09-05T19:28:08.853").getTime()).toBe(
        Date.UTC(2026, 8, 6, 2, 28, 8, 853), // 19:28 PDT is 02:28Z the next day
      );
      expect(parseD1Timestamp(value).toISOString()).toBe("2026-09-05T19:28:08.853Z");
    });
    inTimeZone("Pacific/Kiritimati", () => {
      expect(parseD1Timestamp(value).toISOString()).toBe("2026-09-05T19:28:08.853Z");
      expect(weekKey(parseD1Timestamp(value))).toBe("2026-36");
    });
  });

  it("truncates the microsecond field to milliseconds rather than rejecting it", () => {
    // JS Dates have millisecond resolution; the extra three digits Django
    // wrote are dropped, not rounded. Sub-millisecond precision is
    // irrelevant to a weekly bucket, but an Invalid Date would not be.
    expect(parseD1Timestamp("2026-09-05 19:28:08.123456").getUTCMilliseconds()).toBe(123);
    expect(parseD1Timestamp("2026-09-05 19:28:08.999999").getUTCMilliseconds()).toBe(999);
  });

  // TICKET #7's actual mechanism. Rows written by the port itself carry
  // pyNow()'s Z-suffixed shape; rows from the import do not. Appending "Z"
  // to a value that already ends in one yields "...ZZ", which new Date()
  // turns into an Invalid Date *silently* -- and weekKey() then printed
  // "NaN-NaN" onto the chart. The second assertion is the pre-fix
  // expression, kept so nobody can call the .replace(/Z$/, "") redundant.
  it("accepts a value that already ends in Z, where a blind + \"Z\" would not", () => {
    const value = "2026-09-05 19:28:08.853000Z";
    expect(parseD1Timestamp(value).toISOString()).toBe("2026-09-05T19:28:08.853Z");
    // What the code did before the strip was added:
    expect(new Date(`${value.replace(" ", "T")}Z`).getTime()).toBeNaN();
  });

  // /Z$/ strips exactly ONE trailing Z, and the strip must not be widened to
  // /Z+$/ or trimmed with a loop "for symmetry": a doubled suffix is not a
  // shape either writer produces, so it is corruption and must be skipped
  // rather than silently repaired into a plausible instant.
  it("strips only one trailing Z, so a doubled suffix stays unreadable", () => {
    expect(parseD1Timestamp("2026-09-05 19:28:08.853000ZZ").getTime()).toBeNaN();
    expect(weekKey(parseD1Timestamp("2026-09-05 19:28:08.853000ZZ"))).toBeNull();
  });

  it("reads both stored shapes to the same instant", () => {
    // stats.ts's local copy of this parser says it must "handle both": the
    // import's space-separated naive text and the port's ISO+Z text. If
    // they disagreed, the same need could land in two different weeks
    // depending on which writer created the row.
    const naive = parseD1Timestamp("2026-09-05 19:28:08.853000");
    const suffixed = parseD1Timestamp("2026-09-05T19:28:08.853Z");
    expect(suffixed.getTime()).toBe(naive.getTime());
    expect(weekKey(naive)).toBe(weekKey(suffixed));
  });

  // THE THIRD SHAPE, and the one that proves the appended "Z" does real work
  // for a value that is already T-separated. `new Date("2026-09-05T19:28:08")`
  // -- ISO date-time grammar, no zone designator -- is specified to be read
  // as LOCAL time, unlike the date-only form two tests down, which is UTC.
  // So this is the shape where dropping the append shifts the instant by the
  // machine's offset while still parsing cleanly, and where the suite's
  // pinned TZ=UTC would hide it completely.
  it("reads a T-separated value carrying no Z as UTC, not as local time", () => {
    expect(parseD1Timestamp("2026-09-05T19:28:08.853000").toISOString()).toBe(
      "2026-09-05T19:28:08.853Z",
    );
    inTimeZone("America/Los_Angeles", () => {
      // Proof of the hazard and of the zone: the same text read by the spec's
      // local-time rule is seven hours out in PDT.
      expect(new Date("2026-09-05T19:28:08.853000").getUTCHours()).toBe(2);
      expect(parseD1Timestamp("2026-09-05T19:28:08.853000").toISOString()).toBe(
        "2026-09-05T19:28:08.853Z",
      );
      expect(weekKey(parseD1Timestamp("2026-09-05T19:28:08.853000"))).toBe("2026-36");
    });
  });

  it("handles a value with no fractional part", () => {
    expect(parseD1Timestamp("2026-09-05 19:28:08").toISOString()).toBe("2026-09-05T19:28:08.000Z");
    expect(parseD1Timestamp("2026-09-05T19:28:08Z").toISOString()).toBe("2026-09-05T19:28:08.000Z");
  });

  it("reads a date-only value as UTC midnight", () => {
    // timesince.ts's parseUtc() documents that production D1 genuinely
    // holds `created` values with no time component (a foodbank list page
    // 500'd on one). This parser survives them too, giving midnight -- so
    // such a row still gets a week bucket instead of being dropped.
    expect(parseD1Timestamp("2026-09-05").toISOString()).toBe("2026-09-05T00:00:00.000Z");
    expect(weekKey(parseD1Timestamp("2026-09-05"))).toBe("2026-36");
    // Date-only text that already carries the suffix survives the strip too.
    expect(parseD1Timestamp("2026-09-05Z").toISOString()).toBe("2026-09-05T00:00:00.000Z");
  });

  // "nothing throws" is the property both callers depend on: they test the
  // result via weekKey() returning null, and never wrap the parse in a
  // try/catch. A throwing parser would take out the whole dashboard for one
  // bad row.
  it("returns an Invalid Date for malformed input, and never throws", () => {
    const malformed = [
      "",
      "   ",
      "not a timestamp",
      "2026-13-45 99:99:99", // month 13: rejected outright
      "2026-09-32 00:00:00", // day 32 likewise
      "2026-09-05 19:28:08 extra", // a second space survives into the result
      "2026-09-05  19:28:08", // double space: "...05T 19:28:08Z"
      " 2026-09-05 19:28:08", // a LEADING space is the one that gets rewritten
      "2026-09-05 19:28:08.853000 ", // trailing space lands before the "Z"
      "2026-09-05 19:28:08.853000+00:00", // neither writer emits an offset
      "2026-09-05 19:28:08.853z", // the /Z$/ strip is case-sensitive
    ];
    for (const value of malformed) {
      expect(() => parseD1Timestamp(value), value).not.toThrow();
      expect(parseD1Timestamp(value).getTime(), value).toBeNaN();
      // ...and every one of them is skipped by the callers, not bucketed.
      expect(weekKey(parseD1Timestamp(value)), value).toBeNull();
    }
  });

  // WHERE "unreadable rows are skipped" HAS A SEAM. The separator fix-up is
  // `.replace(" ", "T")` -- one literal ASCII space -- but when the result
  // does not match the ISO grammar V8 falls back to its legacy date parser,
  // and that parser treats a tab or a NO-BREAK SPACE as a separator of its
  // own accord. So a `created` corrupted by a copy-paste through a rich-text
  // field yields a real, plausible-looking bucket, while the ASCII double
  // space in the malformed list above yields none -- precisely because that
  // one DOES get its first space rewritten into a "T" and then satisfies
  // neither grammar.
  //
  // Recorded because the asymmetry is surprising and because it bounds the
  // claim the callers rely on: what gets skipped is what the RUNTIME also
  // rejects, not what this module normalised.
  it("silently accepts whitespace separators the replace() never touched", () => {
    expect(parseD1Timestamp("2026-09-05\t19:28:08").toISOString()).toBe("2026-09-05T19:28:08.000Z");
    expect(weekKey(parseD1Timestamp("2026-09-05\t19:28:08"))).toBe("2026-36");
    // U+00A0 NO-BREAK SPACE, written as an escape so it survives an editor
    // or a linter that would otherwise normalise it back to a plain space.
    expect(parseD1Timestamp("2026-09-05\u00A019:28:08").toISOString()).toBe(
      "2026-09-05T19:28:08.000Z",
    );
    // The ASCII double space, by contrast, is skipped -- same corruption,
    // opposite outcome, because it is the only one the replace() reaches.
    expect(weekKey(parseD1Timestamp("2026-09-05  19:28:08"))).toBeNull();
  });

  // WHERE "never throws" STOPS BEING TRUE. The parameter is typed `string`
  // and NeedForWeeklyCountRow.created is typed `string` too
  // (packages/db/src/dashboards.ts:25), but that is a compile-time promise
  // about a nullable TEXT column read out of D1 at runtime. A single NULL
  // `created` reaches `.replace` on null and throws a TypeError, which the
  // callers do not catch -- so it 500s the whole dashboard, the exact
  // failure mode the null-return design was chosen to avoid.
  //
  // Pinned as current behaviour, not asserted as desirable. If a guard is
  // ever added, this test should change on purpose.
  it("THROWS rather than returning an Invalid Date when handed a non-string", () => {
    expect(() => parseD1Timestamp(null as unknown as string)).toThrow(TypeError);
    expect(() => parseD1Timestamp(undefined as unknown as string)).toThrow(TypeError);
    expect(() => parseD1Timestamp(0 as unknown as string)).toThrow(TypeError);
  });

  // A calendrically impossible date whose FIELDS are all in range does not
  // fail: V8 falls back to legacy parsing and rolls it over. "2026-02-30"
  // becomes 2 March and gets a real, wrong bucket -- week 10 -- instead of
  // being skipped. Python's datetime would have raised ValueError on the
  // same string, so this is a live divergence from the Django ancestor.
  //
  // The codebase already knows about this class of input: stats.ts's
  // parseIsoDate() round-trips through Date.UTC specifically because "the
  // regex alone would pass 2026-02-31" (routes/admin/stats.ts:75-76). This
  // parser does no such check, and that is what is recorded here.
  it("silently rolls impossible-but-in-range dates over instead of skipping them", () => {
    expect(parseD1Timestamp("2026-02-30 00:00:00").toISOString()).toBe("2026-03-02T00:00:00.000Z");
    expect(weekKey(parseD1Timestamp("2026-02-30 00:00:00"))).toBe("2026-10");
    expect(parseD1Timestamp("2026-04-31 12:00:00").toISOString()).toBe("2026-05-01T12:00:00.000Z");
    // Out-of-range FIELDS are still rejected, which is why the boundary is
    // where it is: 30 February parses, month 13 does not.
    expect(parseD1Timestamp("2026-13-01 00:00:00").getTime()).toBeNaN();
  });

  it("survives the calendar-year/ISO-week boundary end to end", () => {
    // The full caller pipeline over the awkward week: a real D1 row shape
    // in, a Django-compatible bucket key out.
    expect(weekKey(parseD1Timestamp("2020-12-31 23:59:59.999999"))).toBe("2020-53");
    expect(weekKey(parseD1Timestamp("2021-01-01 00:00:00.000000"))).toBe("2021-53");
  });
});
