import { afterEach, describe, expect, it, vi } from "vitest";
import { timesince, timesinceAgo } from "./timesince";

// Every expectation in this file was generated by running the real
// django.utils.timesince.timesince() out of the Django install in the
// ancestor repo (/Users/jasoncartwright/Sites/foodcharity/.venv, Django on
// python3.12) with the same two datetimes, so a failure here means the port
// has drifted from Django, not that somebody guessed wrong.
//
// The one place that stops being true is the block marked DIVERGENCE, which
// records where the port and Django genuinely disagree. The cases marked
// JAVASCRIPT QUIRK are the other exception: they pin behaviour that comes out
// of Date.UTC() rather than out of either implementation's own logic.

// Naive UTC, spelled out. `new Date(2026, 8, 5)` would be LOCAL time, and
// this module reads every field with getUTC*; the harness pins TZ=UTC so the
// difference would hide, which is exactly why the dates are built explicitly.
const utc = (y: number, mo: number, d: number, h = 0, mi = 0, s = 0, ms = 0) =>
  new Date(Date.UTC(y, mo - 1, d, h, mi, s, ms));

// Django's avoid_wrapping() replaces the space inside "5 minutes" with a
// non-breaking one so a count never wraps away from its unit, and the port's
// unitText() does the same. Always written as the escape, never as the raw
// character: U+00A0 and a plain space are indistinguishable on screen, and a
// test that compared against the wrong one would assert nothing at all.
const NB = " ";

describe("timesince", () => {
  describe("the future, and anything under a minute", () => {
    // Django's docstring: "If d occurs after now, return '0 minutes'." The
    // public /frag/last-updated endpoint hangs off this: a clock skew of a
    // second between the ETL writer and the Worker must render as a calm
    // "0 minutes", never a negative duration.
    it("returns 0 minutes when d is after now", () => {
      expect(timesince(utc(2026, 9, 5, 12), utc(2026, 9, 5, 11))).toBe(`0${NB}minutes`);
      // Years into the future, not just an hour: a long negative delta must
      // not come back round as a confident "6 years" through the divmod and
      // floor arithmetic below, which is what happens if the guard is written
      // as `=== 0` or is moved after the month calculation.
      expect(timesince(utc(2026, 9, 5), utc(2020, 1, 1))).toBe(`0${NB}minutes`);
    });

    it("returns 0 minutes when d and now are the same instant", () => {
      expect(timesince(utc(2026, 9, 5, 12), utc(2026, 9, 5, 12))).toBe(`0${NB}minutes`);
    });

    // "Seconds and microseconds are ignored" (Django docstring). Minute is
    // the finest unit that exists, so the whole first minute collapses to
    // zero rather than rounding up.
    it("ignores seconds: 59s is still 0 minutes, 60s is 1 minute", () => {
      const d = utc(2026, 9, 5, 12, 0, 0);
      expect(timesince(d, utc(2026, 9, 5, 12, 0, 59))).toBe(`0${NB}minutes`);
      expect(timesince(d, utc(2026, 9, 5, 12, 1, 0))).toBe(`1${NB}minute`);
      expect(timesince(d, utc(2026, 9, 5, 12, 1, 59))).toBe(`1${NB}minute`);
    });

    // Sub-second deltas floor to 0, not to -1: Math.floor() of a positive
    // fraction is 0, and `sinceSeconds <= 0` then short-circuits. This is the
    // realistic shape of a KV-cached `modified` read back microseconds later.
    it("treats a sub-second delta as 0 minutes rather than a negative one", () => {
      expect(timesince(utc(2026, 9, 5, 12, 0, 0, 0), utc(2026, 9, 5, 12, 0, 0, 400))).toBe(`0${NB}minutes`);
    });

    // A SECOND, DIFFERENT ROUTE TO "0 minutes", and the one that is easy to
    // break. A 30-second delta has sinceSeconds = 30, so it does NOT take the
    // `sinceSeconds <= 0` early return: it runs the whole pipeline, ends up
    // with every partial zero, and depends on the `firstNonZero === -1` guard
    // (Django's `for ... else`) to catch that. Delete the guard and the code
    // indexes partials[-1] and UNITS[-1] and throws a TypeError on the most
    // ordinary case there is -- a foodbank edited moments ago.
    it("takes the all-zero-partials path without throwing, and still says 0 minutes", () => {
      const d = utc(2026, 9, 5, 12, 0, 0);
      expect(() => timesince(d, utc(2026, 9, 5, 12, 0, 30))).not.toThrow();
      expect(timesince(d, utc(2026, 9, 5, 12, 0, 30))).toBe(`0${NB}minutes`);
      // One second past d: the smallest positive delta that still reaches the
      // guard rather than the early return.
      expect(timesince(d, utc(2026, 9, 5, 12, 0, 1))).toBe(`0${NB}minutes`);
    });

    // The two zero routes must produce byte-identical output, U+00A0 and all.
    // timesinceAgo's "Under a minute ago" comparison keys off the exact text,
    // so if they ever diverged that branch's behaviour would start depending
    // on which route the caller happened to take.
    it("produces byte-identical output from both zero routes", () => {
      const early = timesince(utc(2026, 9, 5, 12), utc(2026, 9, 5, 11)); // sinceSeconds <= 0
      const allZero = timesince(utc(2026, 9, 5, 12), utc(2026, 9, 5, 12, 0, 30)); // firstNonZero === -1
      expect(early).toBe(allZero);
      expect(early).toBe(`0${NB}minutes`);
    });
  });

  describe("singular and plural per unit", () => {
    // Django uses ngettext per unit, so the count of THAT unit decides its
    // own word -- "1 year, 1 month" mixes two singulars, and "1 hour, 5
    // minutes" mixes a singular with a plural. A single `count === 1` check
    // applied to the whole string would get these wrong.
    it("picks the word from that unit's own count, not the overall total", () => {
      expect(timesince(utc(2026, 9, 5, 12), utc(2026, 9, 5, 13))).toBe(`1${NB}hour`);
      expect(timesince(utc(2026, 9, 5, 12), utc(2026, 9, 5, 13, 5))).toBe(`1${NB}hour, 5${NB}minutes`);
      expect(timesince(utc(2013, 2, 10), utc(2014, 3, 10))).toBe(`1${NB}year, 1${NB}month`);
      expect(timesince(utc(2026, 9, 1), utc(2026, 9, 8))).toBe(`1${NB}week`);
      expect(timesince(utc(2026, 9, 5), utc(2026, 9, 6))).toBe(`1${NB}day`);
      // The mirror image of "1 hour, 5 minutes": a plural leading a singular.
      // An implementation that decided the word once, from the first count,
      // and reused it for both units would satisfy every line above and fail
      // only here.
      expect(timesince(utc(2026, 9, 5, 12), utc(2026, 9, 5, 14, 1))).toBe(`2${NB}hours, 1${NB}minute`);
      expect(timesince(utc(2026, 9, 1, 12), utc(2026, 9, 16, 12))).toBe(`2${NB}weeks, 1${NB}day`);
    });

    it("pluralises every unit above one", () => {
      expect(timesince(utc(2024, 9, 5, 12), utc(2026, 9, 5, 12))).toBe(`2${NB}years`);
      expect(timesince(utc(2025, 10, 5, 12), utc(2026, 9, 5, 12))).toBe(`11${NB}months`);
      expect(timesince(utc(2026, 9, 1, 12), utc(2026, 9, 18, 12))).toBe(`2${NB}weeks, 3${NB}days`);
      expect(timesince(utc(2026, 9, 1), utc(2026, 9, 7, 23))).toBe(`6${NB}days, 23${NB}hours`);
      expect(timesince(utc(2026, 9, 5, 12, 0), utc(2026, 9, 5, 12, 59, 59))).toBe(`59${NB}minutes`);
    });

    // Zero is plural in English ("0 minutes", not "0 minute") and Django's
    // ngettext agrees. The port gets this right only because it tests for
    // exactly one rather than for at most one; a `count <= 1` would read
    // perfectly well in a diff and would put "0 minute ago" under every
    // freshly-edited foodbank on the site.
    it("uses the plural for zero, not the singular", () => {
      const out = timesince(utc(2026, 9, 5, 12), utc(2026, 9, 5, 12));
      expect(out).toBe(`0${NB}minutes`);
      expect(out).not.toBe(`0${NB}minute`);
    });
  });

  describe("avoid_wrapping", () => {
    // The module header claims "spaces within each unit replaced with U+00A0
    // (avoid_wrapping) before joining with ', '". Two different separators in
    // one string is easy to get wrong in either direction, and both directions
    // are visible on the page: an ASCII space inside a unit lets "1" and
    // "hour" wrap onto different lines in the admin's narrow table cells, and
    // a U+00A0 after the comma is a subtly-too-wide gap that never breaks.
    it("uses U+00A0 inside a unit and a plain ', ' between units", () => {
      const out = timesince(utc(2026, 9, 5, 12), utc(2026, 9, 6, 15));
      expect(out).toBe(`1${NB}day, 3${NB}hours`);
      // Counted, not eyeballed, because the assertion above cannot show the
      // difference: exactly two U+00A0 (one per unit) and exactly one ASCII
      // space (the one after the comma).
      expect(out.split(NB)).toHaveLength(3);
      expect(out.split(" ")).toHaveLength(2);
    });

    // The single-unit case has no comma to hide behind, so it is the one that
    // proves the U+00A0 comes from unitText() rather than from the join.
    it("uses U+00A0 even when there is one unit and therefore no join at all", () => {
      const out = timesince(utc(2026, 9, 5, 12), utc(2026, 9, 5, 13));
      expect(out).toBe(`1${NB}hour`);
      expect(out).not.toContain(" "); // not one ASCII space anywhere
      expect(out.split(NB)).toHaveLength(2);
    });

    // Every string the module can emit has to obey the rule, including the
    // two zero routes and the NaN route -- an ASCII space would slip through
    // unnoticed on exactly the outputs nobody looks at.
    it("never emits an ASCII space except the one directly after a comma", () => {
      const outputs = [
        timesince(utc(2026, 9, 5, 12), utc(2026, 9, 5, 11)), // future
        timesince(utc(2026, 9, 5, 12), utc(2026, 9, 5, 12, 0, 30)), // all-zero partials
        timesince(utc(2026, 9, 5, 12), utc(2026, 9, 5, 13, 5)), // two units
        timesince("not a date", utc(2026, 9, 5, 12)), // NaN
      ];
      for (const out of outputs) {
        expect(out.replace(/, /g, "")).not.toContain(" ");
      }
    });
  });

  describe("at most two adjacent units", () => {
    // Django's docstring: '"2 weeks, 3 days" and "1 year, 3 months" are
    // possible outputs, but "2 weeks, 3 hours" and "1 year, 5 days" are not.'
    // The loop stops at the FIRST zero, it does not skip over it to find the
    // next non-zero unit -- so a delta of a year and a week reports only the
    // year, because the months in between are zero.
    it("stops at the first zero unit instead of skipping to the next non-zero one", () => {
      // 1 year, 0 months, 1 week -- the week is dropped.
      expect(timesince(utc(2025, 9, 5, 12), utc(2026, 9, 13, 12))).toBe(`1${NB}year`);
      // 1 week, 0 days, 1 hour -- the hour is dropped.
      expect(timesince(utc(2026, 9, 1), utc(2026, 9, 8, 1))).toBe(`1${NB}week`);
      // 1 day, 0 hours, 5 minutes -- the minutes are dropped. Further down
      // the table than either of the above, so it also catches a break that
      // only ever fired on the leading units.
      expect(timesince(utc(2026, 9, 5, 12), utc(2026, 9, 6, 12, 5))).toBe(`1${NB}day`);
    });

    it("never emits a third unit, however many are non-zero", () => {
      // 11 months, 4 weeks, 2 days: the days are past depth=2.
      expect(timesince(utc(2025, 9, 6, 12), utc(2026, 9, 5, 12))).toBe(`11${NB}months, 4${NB}weeks`);
      // Three CONSECUTIVE non-zero units, so nothing but the depth limit can
      // stop the third being printed: 2 days, 3 hours and 30 minutes. A depth
      // of 3 would render all three here, and counting the separators is what
      // makes that impossible to miss rather than trusting the exact string.
      const three = timesince(utc(2026, 9, 1, 12), utc(2026, 9, 3, 15, 30));
      expect(three).toBe(`2${NB}days, 3${NB}hours`);
      expect(three.split(", ")).toHaveLength(2);
      // And a span with four consecutive non-zero units starting from the top
      // of the table -- 2 years, 1 month, 2 weeks, 5 days -- which is the
      // case a depth bug at the FRONT of the list would show up in.
      const four = timesince(utc(2024, 8, 1, 12), utc(2026, 9, 20, 12));
      expect(four).toBe(`2${NB}years, 1${NB}month`);
      expect(four.split(", ")).toHaveLength(2);
      // Corroborating the "four non-zero units" claim rather than asserting
      // it from a comment: the span from that case's pivot (1 Sep 2026, d
      // shifted by the 2 years and 1 month) to the same `now` really does
      // carry a non-zero weeks and days, so the truncation above is the depth
      // limit doing its job and not two units that happened to be zero.
      expect(timesince(utc(2026, 9, 1, 12), utc(2026, 9, 20, 12))).toBe(`2${NB}weeks, 5${NB}days`);
    });
  });

  describe("calendar-aware year and month arithmetic", () => {
    // The two examples straight out of Django's own docstring: 'There is
    // exactly "1 year, 1 month" between 2013/02/10 and 2014/03/10, but also
    // between 2007/08/10 and 2008/09/10 despite the delta being 393 days in
    // the former case and 397 in the latter.' Any implementation that divided
    // a second-count by 365.25 days would have to give these two different
    // answers, so this pair is the sharpest available test that the port kept
    // Django's calendar arithmetic rather than approximating it.
    it("gives the same answer for 393-day and 397-day year-and-a-month gaps", () => {
      expect(timesince(utc(2013, 2, 10), utc(2014, 3, 10))).toBe(`1${NB}year, 1${NB}month`);
      expect(timesince(utc(2007, 8, 10), utc(2008, 9, 10))).toBe(`1${NB}year, 1${NB}month`);
    });

    // The month is only complete once the same day-of-month AND time-of-day
    // are reached; one second short falls all the way back to weeks, because
    // "4 weeks, 2 days" is what August actually contains. This is the
    // `d.day > now.day or (d.day == now.day and d.time() > now.time())`
    // decrement in Django, and the same guard in the port.
    it("does not credit a month until the exact day and time are reached", () => {
      expect(timesince(utc(2026, 8, 5, 12, 0, 0), utc(2026, 9, 5, 11, 59, 59))).toBe(`4${NB}weeks, 2${NB}days`);
      expect(timesince(utc(2026, 8, 5, 12, 0, 0), utc(2026, 9, 5, 12, 0, 0))).toBe(`1${NB}month`);
    });

    // Both halves of that guard are STRICT comparisons, and loosening either
    // to >= is the single most plausible wrong edit in this function: it reads
    // as a harmless tidy-up in review and it silently costs every foodbank a
    // month on its "last updated" line.
    it("decrements only on a strictly later day-of-month or time-of-day", () => {
      // Same day-of-month, d EARLIER in the day: no decrement, so the month
      // is credited. `dTimeOfDay >= nowTimeOfDay` cannot survive this...
      expect(timesince(utc(2026, 8, 5, 11, 0, 0), utc(2026, 9, 5, 12, 0, 0))).toBe(`1${NB}month`);
      // ...and `d.getUTCDate() >= now.getUTCDate()` cannot survive the exact
      // anniversary in the test above. This is the opposite side: d's day of
      // the month is strictly the later one, so a near-month reports as weeks.
      expect(timesince(utc(2026, 8, 20, 12), utc(2026, 9, 5, 12))).toBe(`2${NB}weeks, 2${NB}days`);
    });

    it("keeps 11 months as months, and rolls to years only at twelve", () => {
      // divmod(total_months, 12): the port's Math.floor/subtract pair has to
      // agree with it exactly, or "11 months" becomes "0 years, 11 months".
      expect(timesince(utc(2025, 10, 5, 12), utc(2026, 9, 5, 12))).toBe(`11${NB}months`);
      expect(timesince(utc(2025, 9, 5, 12), utc(2026, 9, 5, 12))).toBe(`1${NB}year`);
    });

    it("clamps the pivot day to the target month's length", () => {
      // 31 Jan cannot become 31 Feb. Django pivots to min(MONTHS_DAYS[1], 31)
      // = 28 Feb, so 31 Jan -> 1 Mar reads as "1 month" and 31 Jan -> 28 Feb
      // reads as "4 weeks" (the month is not yet complete: day 31 > day 28).
      expect(timesince(utc(2026, 1, 31, 12), utc(2026, 3, 1, 12))).toBe(`1${NB}month`);
      expect(timesince(utc(2026, 1, 31), utc(2026, 2, 28))).toBe(`4${NB}weeks`);
      // The clamp applies to the PIVOT month alone, not to every month the
      // span crosses: 31 Jan -> 31 Mar is a clean two months even though the
      // February in between is short. An implementation that clamped against
      // the shortest intervening month would report "1 month, 4 weeks" here,
      // and would look entirely reasonable doing it.
      expect(timesince(utc(2026, 1, 31), utc(2026, 3, 31))).toBe(`2${NB}months`);
    });

    it("uses a 28-day February even in a leap year, exactly as Django's MONTHS_DAYS does", () => {
      // MONTH_DAYS is a flat table with no leap-year branch, copied from
      // Django's MONTHS_DAYS tuple. 2024 is a leap year and 29 Feb 2024
      // exists, but the pivot still clamps to the 28th. Adding a leap-year
      // correction here would look like a bug fix and would silently break
      // parity with the Django site these strings are compared against.
      expect(timesince(utc(2024, 1, 31), utc(2024, 3, 1))).toBe(`1${NB}month`);
      expect(timesince(utc(2024, 2, 29), utc(2025, 3, 1))).toBe(`1${NB}year`);
      // Starting ON 29 February is unaffected by the table, because the clamp
      // only ever shortens: min(31, 29) is 29, so 29 Feb -> 29 Mar 2024 is a
      // clean month. Pinned so the leap-day case is not assumed to be broken
      // in both directions.
      expect(timesince(utc(2024, 2, 29), utc(2024, 3, 29))).toBe(`1${NB}month`);
    });

    // The `if (pivotMonth > 12) { pivotMonth -= 12; pivotYear += 1 }` branch,
    // which is NOT redundant even though Date.UTC() normalises a month index
    // of 13 or more on its own: MONTH_DAYS[pivotMonth - 1] is read BEFORE
    // that normalisation, so without the wrap it indexes past the end of a
    // twelve-entry table, Math.min(undefined, day) is NaN, and the whole
    // pivot becomes an Invalid Date. Both cases here cross a year boundary.
    it("wraps a pivot month past December into the next year", () => {
      // 30 Nov 2025 -> 28 Feb 2026. total_months 3, decremented to 2 (day 30
      // > day 28), so the pivot is 30 Jan 2026 -- month index 11 + 2 = 13.
      // Drop `pivotYear += 1` and the pivot lands a year early, giving the
      // nonsensical "2 months, 56 weeks"; drop the wrap entirely and it is
      // "2 months, NaN weeks". Neither would throw, so only the exact string
      // catches them.
      expect(timesince(utc(2025, 11, 30), utc(2026, 2, 28))).toBe(`2${NB}months, 4${NB}weeks`);
      // The same wrap with a non-zero year component: 15 Nov 2025 -> 15 Feb
      // 2027 is 15 months, so the pivot is 15 Feb 2027 exactly.
      expect(timesince(utc(2025, 11, 15), utc(2027, 2, 15))).toBe(`1${NB}year, 3${NB}months`);
    });

    // divmod at scale. Nothing caps the year count and the admin does list
    // genuinely old rows, so this pins that the year/month split still holds
    // when total_months is in the thousands rather than the teens -- 1520
    // months here, which has to come out as 126 years and 8 months and not as
    // a rounded 126 with the remainder lost.
    it("handles a century-scale gap without losing the month remainder", () => {
      expect(timesince(utc(1900, 1, 1), utc(2026, 9, 5))).toBe(`126${NB}years, 8${NB}months`);
    });
  });

  describe("UTC, never local time", () => {
    // Every field is read with getUTC*. A local-time reader in a non-UTC zone
    // would see a different day-of-month for these instants and so take a
    // different branch on the month decrement. The vitest config pins TZ=UTC,
    // so this cannot fail here today -- it is here to fail the day somebody
    // swaps a getUTCDate() for a getDate() and the Worker's own (always-UTC)
    // clock stops being the only thing that matters.
    it("straddles a day boundary by UTC clock", () => {
      expect(timesince(utc(2026, 6, 30, 23, 30), utc(2026, 7, 1, 0, 30))).toBe(`1${NB}hour`);
      // Mid-BST, where a local-time reading in London would be an hour out.
      expect(timesince(utc(2026, 7, 15, 0, 30), utc(2026, 7, 15, 2, 30))).toBe(`2${NB}hours`);
    });

    // A version that does NOT depend on the harness's TZ at all, unlike the
    // one above. The answer has to come from the instant, so two Dates built
    // by different routes to the same moment must give the same string: one
    // parsed from an offset-bearing ISO string, one from Date.UTC(). Any
    // implementation that mixed a UTC field read with a local one -- a
    // getUTCDate() next to a getHours(), the realistic form of this mistake
    // -- would tell these two apart in any zone that is not UTC.
    it("reads an instant, not a wall-clock rendering of it", () => {
      const viaOffset = new Date("2026-08-05T13:00:00+01:00"); // 12:00 UTC
      expect(viaOffset.getTime()).toBe(utc(2026, 8, 5, 12).getTime());
      const now = utc(2026, 9, 5, 12);
      expect(timesince(viaOffset, now)).toBe(timesince(utc(2026, 8, 5, 12), now));
      expect(timesince(viaOffset, now)).toBe(`1${NB}month`);
    });
  });

  describe("parsing D1 timestamp strings", () => {
    // The Django/D1 on-disk shape, str(datetime): space separator, six
    // fractional digits (see packages/models/src/pyDatetime.ts). This is what
    // every `created`/`modified`/`edited` column actually holds.
    it("reads Django's str(datetime) format", () => {
      expect(timesince("2026-09-05 12:00:00.000000", utc(2026, 9, 5, 13, 5))).toBe(`1${NB}hour, 5${NB}minutes`);
      // Not "1 day, 3 hours": the 123456us makes d 0.123s earlier than the
      // round time, so the last hour is incomplete and floors away. The
      // fractional field is genuinely parsed and genuinely reaches the
      // arithmetic -- a parser that dropped it would say "3 hours" here.
      // The real Django gives "1 day, 2 hours" for these two datetimes too.
      expect(timesince("2026-09-05 12:00:00.123456", utc(2026, 9, 6, 15))).toBe(`1${NB}day, 2${NB}hours`);
    });

    it("accepts a 'T' separator as well as a space", () => {
      expect(timesince("2026-09-05T12:00:00.000000", utc(2026, 9, 5, 13, 5))).toBe(`1${NB}hour, 5${NB}minutes`);
    });

    // parseUtc's own comment: the "Z" has to come off the WHOLE time part
    // before the split on ".", because with no "." at all it would otherwise
    // land in the seconds field, and Number("00Z") is NaN -- which surfaces
    // as "NaN years, NaN months" on the page, not as an error anyone would
    // spot. Both shapes are covered because they fail through different
    // fields (the seconds field, and the fractional-seconds field).
    it("strips a trailing Z, with and without fractional seconds", () => {
      expect(timesince("2026-09-05T12:00:00Z", utc(2026, 9, 5, 13, 5))).toBe(`1${NB}hour, 5${NB}minutes`);
      expect(timesince("2026-09-05 12:00:00Z", utc(2026, 9, 5, 13, 5))).toBe(`1${NB}hour, 5${NB}minutes`);
      // With a fraction present the Z has to come off the fraction instead;
      // "123456Z" would be NaN microseconds. "4 minutes" rather than "5" is
      // the same 0.123s shortfall as above, and confirms the fraction
      // survived the strip intact rather than being zeroed out by it.
      expect(timesince("2026-09-05T12:00:00.123456Z", utc(2026, 9, 5, 13, 5))).toBe(`1${NB}hour, 4${NB}minutes`);
    });

    // The other half of the same claim -- "D1's own naive-format values (no
    // 'Z') are untouched by this replace" -- which is only worth anything if
    // both spellings land on the same instant. An unanchored /Z/ or a blind
    // slice(0, -1) would corrupt one of the two while leaving the assertions
    // above green, and only comparing the pair catches that.
    it("treats a Z-suffixed value and its naive twin as the same instant", () => {
      const now = utc(2026, 9, 5, 13, 5);
      expect(timesince("2026-09-05T12:00:00.123456Z", now)).toBe(timesince("2026-09-05T12:00:00.123456", now));
      expect(timesince("2026-09-05 12:00:00Z", now)).toBe(timesince("2026-09-05 12:00:00", now));
    });

    // The production incident named in parseUtc's comment: a foodbank list
    // page 500'd because some stored dates genuinely have no time component
    // at all. rawTimePart is `undefined` there (not ""), so the fallback
    // cannot be a `|| ""` on the split result. Midnight is the reading.
    it("treats a date-only value as midnight rather than throwing", () => {
      expect(() => timesince("2026-08-01")).not.toThrow();
      expect(timesince("2026-08-01", utc(2026, 9, 5, 12))).toBe(`1${NB}month`);
      expect(timesince("2026-09-05", utc(2026, 9, 5, 1))).toBe(`1${NB}hour`);
      // Midnight exactly, not noon and not "start of the working day": the
      // gap to 23:59 on the same date is the whole day less a minute. The
      // one-hour assertion above would survive several wrong defaults; this
      // one pins the value.
      expect(timesince("2026-09-05", utc(2026, 9, 5, 23, 59))).toBe(`23${NB}hours, 59${NB}minutes`);
    });

    // A short fraction is padded on the RIGHT, because ".5" is 500000
    // microseconds (half a second), not 5. Padding on the left would make it
    // 5 microseconds and quietly shift sub-second comparisons.
    it("pads a short fractional-seconds field on the right", () => {
      // 12:00:00.5 -> the delta to 12:01:00 is 59.5s, which floors to under a
      // minute. If ".5" were read as 5us the delta would be a full 60s and
      // this would say "1 minute".
      expect(timesince("2026-09-05 12:00:00.5", utc(2026, 9, 5, 12, 1, 0))).toBe(`0${NB}minutes`);
      expect(timesince("2026-09-05 12:00:00.000000", utc(2026, 9, 5, 12, 1, 0))).toBe(`1${NB}minute`);
    });

    // The rest of that same expression: `.slice(0, 6)` after the pad, and
    // `Math.floor(us / 1000)` after that. Nothing upstream promises exactly
    // six digits -- SQLite hands back whatever text was written into the
    // column -- so both the too-long and the too-precise cases need a defined
    // answer rather than a NaN leaking into the arithmetic.
    it("truncates a fraction longer than six digits, and floors sub-millisecond precision away", () => {
      const oneMinuteLater = utc(2026, 9, 5, 12, 1, 0);
      // Seven digits, sliced back to 123456us = 123ms, so the delta is 59.877s
      // and still under a minute. Without the slice, Number("1234567") is
      // 1234ms -- over a second -- and the answer moves the other way.
      expect(timesince("2026-09-05 12:00:00.1234567", oneMinuteLater)).toBe(`0${NB}minutes`);
      expect(timesince("2026-09-05 12:00:00.9999999", oneMinuteLater)).toBe(`0${NB}minutes`);
      // 999 microseconds is under a millisecond, and Date's resolution stops
      // at milliseconds, so it floors away entirely and the delta is a clean
      // 60 seconds. A Math.round() here would borrow a millisecond and turn
      // this into "0 minutes".
      expect(timesince("2026-09-05 12:00:00.000999", oneMinuteLater)).toBe(`1${NB}minute`);
      // A trailing "." with nothing after it: frac is "" and therefore falsy,
      // so the millis branch is skipped rather than relying on Number("")
      // happening to be 0.
      expect(timesince("2026-09-05 12:00:00.", oneMinuteLater)).toBe(`1${NB}minute`);
    });

    it("agrees with the equivalent Date object", () => {
      const now = utc(2026, 9, 5, 12);
      expect(timesince("2025-06-05 12:00:00.000000", now)).toBe(timesince(utc(2025, 6, 5, 12), now));
      expect(timesince("2025-06-05 12:00:00.000000", now)).toBe(`1${NB}year, 3${NB}months`);
      // Agreement at millisecond level too, not just to the second: the
      // string path runs the padEnd/slice/floor chain and the Date path does
      // not, so this is the only place the two are pinned to the same instant
      // at the precision the month-boundary guard actually reads.
      const boundary = utc(2026, 9, 5, 12, 1, 0);
      expect(timesince("2026-09-05 12:00:00.500000", boundary)).toBe(
        timesince(utc(2026, 9, 5, 12, 0, 0, 500), boundary),
      );
      expect(timesince("2026-09-05 12:00:00.500000", boundary)).toBe(`0${NB}minutes`);
    });
  });

  describe("malformed and missing input", () => {
    // Not an endorsement -- a record of what a bad row does today. parseUtc
    // has no validation, so an unparseable value becomes an Invalid Date,
    // every arithmetic result becomes NaN, `NaN !== 0` makes the
    // first-non-zero search stop at index 0, and the caller gets the string
    // below rendered into the page. It does NOT throw, which is what keeps a
    // single bad row from 500ing a whole list page the way the missing
    // time-component rows once did.
    const NAN_TEXT = `NaN${NB}years, NaN${NB}months`;

    it("returns NaN text rather than throwing on an unparseable value", () => {
      const now = utc(2026, 9, 5, 12);
      expect(() => timesince("not a date", now)).not.toThrow();
      expect(timesince("not a date", now)).toBe(NAN_TEXT);
      // A timezone offset is not one of the shapes parseUtc handles: the
      // "+00:00" contaminates the seconds field. Worth pinning, because
      // "looks like a valid ISO timestamp" is exactly the kind of value a
      // future writer could introduce upstream without noticing.
      expect(timesince("2026-09-05T12:00:00+00:00", now)).toBe(NAN_TEXT);
      expect(timesince("2026-09-05T12:00:00-05:00", now)).toBe(NAN_TEXT);
      expect(timesince("", now)).toBe(NAN_TEXT);
      // Only an UPPERCASE Z is stripped: /Z$/ carries no `i` flag. ISO 8601
      // permits the lowercase spelling, so a hand-written or third-party
      // "...12:00:00z" silently becomes NaN instead of parsing.
      expect(timesince("2026-09-05T12:00:00z", now)).toBe(NAN_TEXT);
      // A partial date. The date-only fallback covers "YYYY-MM-DD" only: with
      // no day at all the destructure yields undefined and poisons Date.UTC().
      expect(timesince("2026-09", now)).toBe(NAN_TEXT);
      // Whitespace is tolerated nowhere, because the split on /[ T]/ treats
      // every space as the date/time separator -- a leading space empties the
      // date part, and a doubled space makes the time part "" rather than
      // undefined, which is not the case the midnight fallback covers.
      expect(timesince(" 2026-09-05 12:00:00", now)).toBe(NAN_TEXT);
      expect(timesince("2026-09-05  12:00:00", now)).toBe(NAN_TEXT);
    });

    it("returns NaN text for an Invalid Date object too", () => {
      expect(timesince(new Date(Number.NaN), utc(2026, 9, 5, 12))).toBe(NAN_TEXT);
      // One millisecond past the largest timestamp a Date can hold is also an
      // Invalid Date, and takes the same route rather than overflowing into a
      // plausible-looking number of years.
      expect(timesince(new Date(8640000000000001), utc(2026, 9, 5, 12))).toBe(NAN_TEXT);
    });

    // JAVASCRIPT QUIRK, pinned because it is invisible. Date.UTC() maps a
    // year of 0-99 onto 1900-1999, so a two-digit year neither fails loudly
    // nor means year 26: it means 1926, and the page shows a confident, wrong
    // "100 years". Nothing in this module can fix that (Date.UTC is the one
    // doing it, where Django's strptime would have rejected the value), but
    // anyone debugging an absurd year count needs it written down somewhere.
    it("silently reads a two-digit year as 19xx rather than rejecting it", () => {
      expect(timesince("26-09-05", utc(2026, 9, 5))).toBe(`100${NB}years`);
    });

    // The same lenience for out-of-range time fields: Date.UTC() rolls 99
    // hours / 99 minutes / 99 seconds forward into the following days instead
    // of returning Invalid Date, so a corrupt row reads as a plausible date
    // several days off. 2026-09-05 99:99:99 normalises to 2026-09-09 04:40:39,
    // which is 3 years and 3 months before 2030-01-01.
    it("normalises out-of-range time fields forward instead of rejecting them", () => {
      expect(timesince("2026-09-05 99:99:99", utc(2030, 1, 1))).toBe(`3${NB}years, 3${NB}months`);
    });

    // CURRENT BEHAVIOUR, and the honest limit of the "a bad row must not 500
    // the page" property above: the no-throw guarantee covers bad STRINGS
    // only. A null or an undefined -- a genuinely NULL timestamp column,
    // which D1 hands back as null however the model types it -- skips the
    // `typeof === "string"` branch and goes straight into `d.getTime()`.
    // Two call sites already guard for this by hand (admin/foodbankCheck.ts
    // and admin/order.ts both write `x ? timesince(x) : null`); the rest do
    // not. Reported rather than fixed, per this file's rules.
    it("throws, rather than returning NaN text, for a null or undefined date", () => {
      const now = utc(2026, 9, 5, 12);
      expect(() => timesince(null as unknown as string, now)).toThrow(TypeError);
      expect(() => timesince(undefined as unknown as string, now)).toThrow(TypeError);
      // A numeric timestamp is not a string either -- a plausible slip, since
      // Date.now() returns one -- so it is treated as a Date and throws too.
      expect(() => timesince(0 as unknown as string, now)).toThrow(TypeError);
      // And a null `now`, for symmetry: the parameter has a default, but a
      // default only fires for `undefined`, never for an explicit null.
      expect(() => timesince("2026-09-05 12:00:00", null as unknown as Date)).toThrow(TypeError);
    });

    // ...whereas an explicit `undefined` for `now` DOES take the default,
    // which is the difference that makes the null case above a real hazard
    // rather than a typing curiosity: the two look interchangeable at a call
    // site and behave nothing alike.
    it("still applies the default when `now` is explicitly undefined", () => {
      const twoHoursAgo = new Date(Date.now() - 2 * 3600 * 1000);
      expect(timesince(twoHoursAgo, undefined)).toBe(`2${NB}hours`);
    });
  });

  describe("extremes of the Date range", () => {
    // Epoch zero is a valid instant, not a missing value. `new Date(0)` looks
    // falsy to none of JavaScript but its timestamp is 0, which is exactly
    // the sort of value a `total || fallback` or a truthiness check further
    // down the pipeline would swallow. The arithmetic has to treat it as an
    // ordinary date.
    it("treats the Unix epoch as a real date, not as a missing one", () => {
      expect(timesince(new Date(0), utc(1970, 1, 2))).toBe(`1${NB}day`);
      expect(timesince("1970-01-01 00:00:00.000000", utc(1970, 2, 1))).toBe(`1${NB}month`);
    });

    // The largest instant a JS Date can hold (8.64e15 ms, year 275760). The
    // point is that the year count stays an exact integer: at this magnitude
    // an implementation that reached the answer by dividing a seconds count
    // would land on a neighbouring year, while the calendar arithmetic here
    // cannot.
    it("stays exact at the far end of the Date range", () => {
      expect(timesince(new Date(0), new Date(8640000000000000))).toBe(`273790${NB}years, 8${NB}months`);
    });
  });

  describe("the default `now`", () => {
    afterEach(() => {
      vi.useRealTimers();
    });

    // Most call sites (api1.ts, admin/foodbankDetail.ts, admin/order.ts) omit
    // `now` entirely and rely on the `= new Date()` default, so a change that
    // made the parameter required would break them at runtime, not at build.
    it("defaults to the current time", () => {
      const twoHoursAgo = new Date(Date.now() - 2 * 3600 * 1000);
      expect(timesince(twoHoursAgo)).toBe(`2${NB}hours`);
      // A date in the future still takes the "0 minutes" branch.
      expect(timesince(new Date(Date.now() + 86400 * 1000))).toBe(`0${NB}minutes`);
    });

    // The sharper version of the same idea. A default evaluated ONCE --
    // hoisted to a module constant, or memoised "to avoid allocating a Date
    // per call" -- passes the test above perfectly, and then pins every
    // request an isolate ever serves to that isolate's cold-start time, so
    // /frag/last-updated freezes at whatever it first said. Moving the clock
    // between two otherwise identical calls is the only thing that tells the
    // two implementations apart.
    it("re-reads the clock on every call, not once at module load", () => {
      vi.useFakeTimers();
      const d = "2026-09-05 12:00:00.000000";
      vi.setSystemTime(utc(2026, 9, 5, 13, 0, 0));
      expect(timesince(d)).toBe(`1${NB}hour`);
      vi.setSystemTime(utc(2026, 9, 6, 15, 30, 0));
      expect(timesince(d)).toBe(`1${NB}day, 3${NB}hours`);
      vi.setSystemTime(utc(2027, 10, 5, 12, 0, 0));
      expect(timesince(d)).toBe(`1${NB}year, 1${NB}month`);
    });
  });

  describe("DIVERGENCE from Django: sub-second times on the month boundary", () => {
    // Django compares `d.time() > now.time()`, which includes microseconds.
    // The port compares hour/minute/second only (dTimeOfDay/nowTimeOfDay), so
    // when d and now share a day-of-month and an H:M:S but differ in
    // milliseconds, the port credits a whole month that Django does not.
    //
    // Verified against the real Django: timesince(2026-01-15 10:00:00.500000,
    // 2026-02-15 10:00:00) is "4 weeks, 2 days" there, and "1 month" here.
    //
    // Pinned rather than fixed, per the rules for this file. It needs a
    // millisecond-exact collision on the same day-of-month to trigger, so it
    // has essentially no chance of firing on real D1 data.
    it("credits a month where Django would say 4 weeks, 2 days", () => {
      const d = utc(2026, 1, 15, 10, 0, 0, 500);
      const now = utc(2026, 2, 15, 10, 0, 0, 0);
      expect(timesince(d, now)).toBe(`1${NB}month`);
    });

    // The divergence is one-directional, and bounding it is what makes the
    // "essentially no chance" claim above checkable rather than a hope. When
    // it is `now` that carries the extra milliseconds, neither implementation
    // decrements and both say "1 month"...
    it("agrees with Django when it is `now` that carries the milliseconds", () => {
      expect(timesince(utc(2026, 1, 15, 10, 0, 0, 0), utc(2026, 2, 15, 10, 0, 0, 500))).toBe(`1${NB}month`);
    });

    // ...and once the difference reaches a whole second it is inside what
    // dTimeOfDay/nowTimeOfDay can see, so the port matches Django again. The
    // divergence therefore lives strictly below one second, on a shared
    // day-of-month, which is the entire blast radius.
    it("matches Django again as soon as the difference reaches a whole second", () => {
      expect(timesince(utc(2026, 1, 15, 10, 0, 1), utc(2026, 2, 15, 10, 0, 0))).toBe(`4${NB}weeks, 2${NB}days`);
    });
  });
});

describe("timesinceAgo", () => {
  // The real values from packages/templates/src/generated/locales/cy.json,
  // inlined so these tests do not break when a catalogue is regenerated.
  const cy = { ago: "yn ôl", "Under a minute ago": "O dan funud yn ôl" };

  // givefood/views.py frag(): `"%s %s" % (timesince_text, _("ago"))`. The
  // space before "ago" is a plain one (it is the format string's own), while
  // the space inside the unit stays non-breaking.
  it("appends the translated 'ago' to the timesince text", () => {
    expect(timesinceAgo("2026-09-05 12:00:00.000000", utc(2026, 9, 5, 13, 0), {})).toBe(`1${NB}hour ago`);
    expect(timesinceAgo("2026-09-05 12:00:00.000000", utc(2026, 9, 6, 15, 0), {})).toBe(`1${NB}day, 3${NB}hours ago`);
  });

  // The separator before "ago" is the one ASCII space in a single-unit
  // string, and it has to stay ASCII because Django's format string is
  // "%s %s". Spelled out separately because the `toBe` above cannot show
  // which kind of space it is, and copying a U+00A0 in there by accident is
  // exactly how the "Under a minute ago" bug below happened in the first place.
  it("joins on an ASCII space, not on the unit's U+00A0", () => {
    const out = timesinceAgo("2026-09-05 12:00:00.000000", utc(2026, 9, 5, 13, 0), {});
    expect(out.endsWith(" ago")).toBe(true);
    expect(out.endsWith(`${NB}ago`)).toBe(false);
    expect(out.split(" ")).toHaveLength(2);
  });

  it("uses the catalogue's 'ago' when one is loaded", () => {
    expect(timesinceAgo("2026-09-05 12:00:00.000000", utc(2026, 9, 5, 13, 0), cy)).toBe(`1${NB}hour yn ôl`);
  });

  // THE DOCUMENTED TRANSLATION GAP, from this module's own comment: the unit
  // words come from Django's bundled core catalogues, which were never
  // extracted into packages/templates/locale/*/django.po. So a Welsh page
  // gets a Welsh "yn ol" wrapped around an English "hours". Asserting it
  // keeps the gap visible instead of letting it look like a rendering bug the
  // next time somebody views /cy/frag/last-updated.
  it("leaves the unit words in English on a non-English locale", () => {
    const out = timesinceAgo("2026-09-05 12:00:00.000000", utc(2026, 9, 5, 15, 30), cy);
    expect(out).toBe(`3${NB}hours, 30${NB}minutes yn ôl`);
    expect(out).toContain("hours");
    // And the gap cannot be closed from this side: timesince() is English-only
    // by design and never consults a catalogue, so a catalogue that DOES carry
    // the unit words changes nothing. That is the module header's "English
    // locale only" claim, made falsifiable rather than taken on trust.
    const cyPlusUnits = { ...cy, hours: "oriau", minutes: "munudau" };
    expect(timesinceAgo("2026-09-05 12:00:00.000000", utc(2026, 9, 5, 15, 30), cyPlusUnits)).toBe(out);
  });

  it("falls back to the English msgid when the catalogue has no entry", () => {
    // translate() returns the msgid for a missing (or empty) msgstr, so an
    // incomplete catalogue degrades to English rather than to a blank string
    // -- a blank /frag/last-updated body is indistinguishable from a failed
    // fetch on the client side.
    expect(timesinceAgo("2026-09-05 12:00:00.000000", utc(2026, 9, 5, 13, 0), { ago: "" })).toBe(`1${NB}hour ago`);
    // A catalogue of entirely unrelated keys is the same case, and is what an
    // English request actually passes: loadCatalogue() returns {} for "en".
    expect(timesinceAgo("2026-09-05 12:00:00.000000", utc(2026, 9, 5, 13, 0), { Go: "Ewch" })).toBe(`1${NB}hour ago`);
  });

  describe("the 'Under a minute ago' branch", () => {
    // CURRENT BEHAVIOUR, PINNED DELIBERATELY -- this reads like a bug and is
    // one, but it is a FAITHFUL port of the same bug in the Django original.
    //
    // timesince() returns "0<U+00A0>minutes" (avoid_wrapping's non-breaking
    // space), and both implementations compare it against a literal built
    // with an ASCII space:
    //
    //   Django   if timesince_text == "0 %s" % (_("minutes")):   # never true
    //   here     if (raw === "0 minutes")                        # never true
    //
    // Confirmed by running the real Django: that equality evaluates to False.
    // So the "Under a minute ago" string is unreachable in BOTH codebases and
    // the endpoint serves "0 minutes ago" instead. Repairing it here alone
    // would break byte parity with the site being replaced, so it is reported
    // rather than fixed.
    it("does not fire, so a fresh edit renders as '0 minutes ago'", () => {
      const out = timesinceAgo("2026-09-05 12:00:00.000000", utc(2026, 9, 5, 12, 0, 30), {});
      expect(out).toBe(`0${NB}minutes ago`);
      expect(out).not.toBe("Under a minute ago");
    });

    it("does not fire on a non-English locale either", () => {
      expect(timesinceAgo("2026-09-05 12:00:00.000000", utc(2026, 9, 5, 12, 0, 30), cy)).toBe(`0${NB}minutes yn ôl`);
    });

    // Nor by the OTHER route to "0 minutes" -- a timestamp in the future,
    // which takes the `sinceSeconds <= 0` early return instead of the
    // all-zero-partials one. Both routes emit the same U+00A0 string, so both
    // miss the literal, and clock skew between the ETL writer and the Worker
    // makes this route reachable in production rather than theoretical.
    it("does not fire for a future timestamp either", () => {
      expect(timesinceAgo("2026-09-05 14:00:00.000000", utc(2026, 9, 5, 12), {})).toBe(`0${NB}minutes ago`);
    });

    // The U+00A0 is the whole reason the branch is dead: the count is right,
    // the word is right, only the separator differs. Spelling both sides out
    // means that if somebody ever repairs it -- in either direction, by
    // putting a U+00A0 in the literal or by dropping avoid_wrapping -- the
    // test above fails loudly and this comment explains why.
    it("is dead because of the U+00A0, not because of the count or the word", () => {
      const raw = timesince(utc(2026, 9, 5, 12), utc(2026, 9, 5, 12, 0, 30));
      expect(raw).toBe(`0${NB}minutes`);
      expect(raw).not.toBe("0 minutes"); // the literal timesinceAgo tests against
      expect(raw.replace(NB, " ")).toBe("0 minutes");
      // Same length, one code point apart: as close as two unequal strings
      // can be, which is precisely why the bug has survived upstream so long.
      expect(raw).toHaveLength("0 minutes".length);
      expect(raw.codePointAt(1)).toBe(0x00a0);
    });

    // A wiring failure, not a missing translation: the catalogue entry the
    // dead branch would have used is present and reachable through the same
    // translate() the "ago" beside it goes through, and it still never
    // appears in the output. Pinned so that whoever repairs the branch knows
    // the Welsh string is already sitting there waiting for it, and so that
    // "the translation is missing" is ruled out as an explanation.
    it("has a reachable 'Under a minute ago' translation that the output never uses", () => {
      const out = timesinceAgo("2026-09-05 12:00:00.000000", utc(2026, 9, 5, 12, 0, 30), cy);
      expect(out).not.toContain("O dan funud");
      // The same catalogue, same lookup, from the branch that IS live -- so
      // the entry above is not being missed for want of a working catalogue.
      expect(timesinceAgo("2026-09-05 12:00:00.000000", utc(2026, 9, 5, 13, 0), cy)).toContain("yn ôl");
    });
  });

  it("propagates the same parsing rules as timesince", () => {
    // timesinceAgo is a thin wrapper: it must not re-parse or pre-normalise
    // the string itself, or the date-only production case would 500 here
    // while working in timesince().
    expect(timesinceAgo("2026-09-05", utc(2026, 9, 5, 3, 0), {})).toBe(`3${NB}hours ago`);
    expect(timesinceAgo("2026-09-05T12:00:00Z", utc(2026, 9, 5, 13, 0), {})).toBe(`1${NB}hour ago`);
    // Including the bad-row behaviour: NaN text with "ago" appended, not a
    // thrown error. /frag/last-updated is fetched by JS on every page of the
    // site, so an unparseable `modified` on the latest Foodbank row has to
    // stay a 200 with ugly text rather than becoming a 500.
    expect(timesinceAgo("not a date", utc(2026, 9, 5, 12), {})).toBe(`NaN${NB}years, NaN${NB}months ago`);
    expect(timesinceAgo("not a date", utc(2026, 9, 5, 12), cy)).toBe(`NaN${NB}years, NaN${NB}months yn ôl`);
  });

  // The wrapper takes `now` as a REQUIRED parameter and has to actually use
  // it -- unlike timesince(), it has no default to fall back on. Fake timers
  // put the real clock a century away from the `now` passed in, so a wrapper
  // that ignored its argument and called new Date() itself would produce a
  // wildly wrong string here rather than a subtly wrong one that could be
  // mistaken for a rounding difference.
  it("uses the `now` it is given rather than the wall clock", () => {
    vi.useFakeTimers();
    try {
      vi.setSystemTime(utc(2126, 1, 1));
      expect(timesinceAgo("2026-09-05 12:00:00.000000", utc(2026, 9, 5, 13, 0), {})).toBe(`1${NB}hour ago`);
    } finally {
      vi.useRealTimers();
    }
  });
});
