#!/usr/bin/env python3
"""
Generate a `SECRET_NAME=value` file for `wrangler deploy --secrets-file`,
for the site Worker (givefood2) or the jobs Worker (givefood2-jobs), by
pulling values from Django's live Postgres GfCredential table by name --
same source, same read-only connection pattern as tools/pg-to-d1/
extract_core.py.

Not every required secret has a Postgres source. Three kinds, handled
differently:

  - "db"       Pulled from GfCredential.cred_value by cred_name (the
               latest row, matching get_cred()'s own `.latest("created")`).
  - "manual"   Lives outside Postgres entirely -- Google Cloud Console,
               Meta's WhatsApp Business dashboard. Never guessed at:
               written as a commented-out placeholder line naming where
               to get it, so `wrangler deploy --secrets-file` neither sees
               nor sets an empty value for it.
  - "generate" Self-generated by this port with no Django source at all
               (SESSION_HMAC_KEY, CSRF_SECRET). SKIPPED BY DEFAULT: both
               are already set on the live site Worker, and a fresh
               random value here would invalidate every outstanding
               session cookie / CSRF token rather than matching what's
               deployed. Only produced with --generate-missing, for a
               genuinely from-scratch deploy.

Read-only against Postgres throughout (a read-only transaction, belt and
braces against this ever being extended to write anything). Requires
foodcharity/.env readable (DB_HOST, DB_NAME, DB_USER, DB_PASS) -- override
with FOODCHARITY_ENV_PATH the same way extract_core.py does.

Usage:
    uv run --with psycopg2-binary python tools/secrets-file/generate_secrets_file.py jobs
    uv run --with psycopg2-binary python tools/secrets-file/generate_secrets_file.py site
    uv run --with psycopg2-binary python tools/secrets-file/generate_secrets_file.py both --generate-missing

Writes to the path given by --out, defaulting to
<repo>/../secrets-<worker>.env (deliberately OUTSIDE the repo, so a stray
`git add -A` can't pick it up). Never commit the output file. Delete it
once `wrangler deploy --secrets-file` has run.

This script only ever PRINTS secret NAMES and outcomes (found / missing /
manual / generated), never values, so running it doesn't put real secret
material into your terminal scrollback beyond the output file itself.
"""
import argparse
import os
import secrets as pysecrets
import sys
from dataclasses import dataclass
from pathlib import Path

FOODCHARITY_ENV_PATH = os.path.expanduser(
    os.environ.get("FOODCHARITY_ENV_PATH", "~/Sites/foodcharity/.env")
)


@dataclass(frozen=True)
class SecretSpec:
    worker_name: str  # SCREAMING_SNAKE_CASE name wrangler secret expects
    source: str  # "db" | "manual" | "generate"
    cred_name: str = ""  # GfCredential.cred_name, when source == "db"
    note: str = ""  # shown for "manual" / "generate"


# gfadmin/views.py, givefood/utils/*.py, givefood/views.py, givefood/
# middleware.py -- every cred_name below is a literal get_cred("...") call
# site, grepped, not guessed. Traced 2026-09-04 for the jobs Worker's
# first deploy; the site Worker's own list is a byproduct of the same pass
# (its secrets are all already set -- this only matters again for a
# from-scratch redeploy).

JOBS_SECRETS = [
    # crawlers.py:439-445's need_check_kwargs -- the needcheck extraction
    # call specifically, NOT openrouter()'s "openrouter_needtestbed"
    # default (a different feature's key).
    SecretSpec("OPENROUTER_KEY", "db", "openrouter_liveneed"),
    SecretSpec("GCP_TRANSLATE_KEY", "db", "gcp_translate_key"),
    SecretSpec("EW_CHARITY_KEY", "db", "ew_charity_api_key"),
    SecretSpec("SCOT_CHARITY_KEY", "db", "scot_charity_api_key"),
    SecretSpec("POSTMARK_TOKEN", "db", "postmark_server_token"),
    SecretSpec("WHATSAPP_TOKEN", "db", "whatsapp_accesstoken"),
    SecretSpec("FIREBASE_SERVICE_ACCOUNT", "db", "firebase_service_account"),
    SecretSpec("VAPID_PRIVATE_KEY", "db", "VAPID_PRIVATE_KEY"),
    SecretSpec("VAPID_PUBLIC_KEY", "db", "VAPID_PUBLIC_KEY"),
    SecretSpec("VAPID_ADMIN_EMAIL", "db", "VAPID_ADMIN_EMAIL"),
    SecretSpec("GMAP_STATIC_KEY", "db", "gmap_static_key"),
    SecretSpec("GMAP_PLACES_KEY", "db", "gmap_places_key"),
    SecretSpec("GMAP_GEOCODE_KEY", "db", "gmap_geocode_key"),
    SecretSpec("CF_API_KEY", "db", "cf_api_key"),
    SecretSpec("CF_ZONE_ID", "db", "cf_zone_id"),
    SecretSpec("GEMINI_API_KEY", "db", "gemini_api_key"),
]

SITE_SECRETS = [
    SecretSpec("GMAP_GEOCODE_KEY", "db", "gmap_geocode_key"),
    SecretSpec("VAPID_PUBLIC_KEY", "db", "VAPID_PUBLIC_KEY"),
    SecretSpec("TURNSTILE_SECRET", "db", "turnstile_secret"),
    SecretSpec("POSTMARK_TOKEN", "db", "postmark_server_token"),
    SecretSpec("SUBSCRIBER_SALT", "db", "salt"),
    SecretSpec(
        "CSRF_SECRET",
        "generate",
        note="self-generated, no Django source -- already set on the live "
        "site Worker; regenerating invalidates every outstanding CSRF token",
    ),
    SecretSpec("WHATSAPP_WEBHOOKVERIFYTOKEN", "db", "whatsapp_webhookverifytoken"),
    SecretSpec(
        "WHATSAPP_APP_SECRET",
        "manual",
        note="Meta WhatsApp Business dashboard -> App Secret. Django never "
        "verified webhook signatures, so there is no Postgres source.",
    ),
    SecretSpec(
        "GOOGLE_OAUTH_CLIENT_SECRET",
        "manual",
        note="Google Cloud Console, OAuth client "
        "927281004707-*.apps.googleusercontent.com. Django's sign-in flow "
        "never used a client secret at all.",
    ),
    SecretSpec(
        "SESSION_HMAC_KEY",
        "generate",
        note="self-generated, no Django source -- already set on the live "
        "site Worker; regenerating signs every admin session cookie invalid",
    ),
    SecretSpec("MAPIT_KEY", "db", "mapit_key"),
    SecretSpec("GMAP_PLACES_KEY", "db", "gmap_places_key"),
    SecretSpec("GMAP_STATIC_KEY", "db", "gmap_static_key"),
    SecretSpec("CF_API_KEY", "db", "cf_api_key"),
    SecretSpec("CF_ZONE_ID", "db", "cf_zone_id"),
]

WORKERS = {"jobs": JOBS_SECRETS, "site": SITE_SECRETS}


def load_env(path):
    env = {}
    for line in open(path):
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        env[k] = v.strip().strip('"').strip("'")
    return env


def fetch_cred_values(cur, cred_names):
    """One query for every distinct cred_name this run needs, latest row
    per name -- not one query per secret. Mirrors get_cred()'s own
    `.latest("created")` semantics exactly (DISTINCT ON + ORDER BY is
    Postgres's equivalent of "the newest row per group")."""
    if not cred_names:
        return {}
    cur.execute(
        """
        SELECT DISTINCT ON (cred_name) cred_name, cred_value
        FROM givefood_gfcredential
        WHERE cred_name = ANY(%s)
        ORDER BY cred_name, created DESC
        """,
        (list(cred_names),),
    )
    return dict(cur.fetchall())


def build_file(specs, cur, generate_missing):
    cred_names = {s.cred_name for s in specs if s.source == "db"}
    found = fetch_cred_values(cur, cred_names)

    lines = []
    outcomes = []  # (name, outcome) for the stderr summary -- names only
    for spec in specs:
        if spec.source == "db":
            value = found.get(spec.cred_name)
            if value is None:
                lines.append(f"# {spec.worker_name}= # NOT FOUND: no GfCredential row named {spec.cred_name!r}")
                outcomes.append((spec.worker_name, "MISSING (no such GfCredential row)"))
            else:
                lines.append(f"{spec.worker_name}={value}")
                outcomes.append((spec.worker_name, f"found (GfCredential {spec.cred_name!r})"))
        elif spec.source == "manual":
            lines.append(f"# {spec.worker_name}= # MANUAL: {spec.note}")
            outcomes.append((spec.worker_name, "manual -- see note in file"))
        elif spec.source == "generate":
            if generate_missing:
                value = pysecrets.token_urlsafe(32)
                lines.append(f"{spec.worker_name}={value}")
                outcomes.append((spec.worker_name, "GENERATED FRESH -- rotation risk, see note in file"))
            else:
                lines.append(f"# {spec.worker_name}= # SKIPPED (--generate-missing to include): {spec.note}")
                outcomes.append((spec.worker_name, "skipped (pass --generate-missing to generate)"))
    return lines, outcomes


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("worker", choices=["site", "jobs", "both"])
    parser.add_argument(
        "--generate-missing",
        action="store_true",
        help="Generate fresh random values for self-generated secrets (CSRF_SECRET, SESSION_HMAC_KEY) "
        "instead of skipping them. Only use this for a from-scratch deploy -- on an already-deployed "
        "Worker it produces a value that will not match what is live.",
    )
    parser.add_argument(
        "--out-dir",
        default=str(Path(FOODCHARITY_ENV_PATH).expanduser().parent.parent),
        help="Directory to write secrets-<worker>.env into. Defaults to the parent of ~/Sites/foodcharity, "
        "i.e. OUTSIDE both this repo and that one.",
    )
    args = parser.parse_args()

    try:
        import psycopg2
    except ImportError:
        sys.exit("psycopg2 not installed -- run with: uv run --with psycopg2-binary python " + sys.argv[0])

    env = load_env(FOODCHARITY_ENV_PATH)
    conn = psycopg2.connect(
        host=env["DB_HOST"], dbname=env["DB_NAME"], user=env["DB_USER"], password=env["DB_PASS"],
        port=5432, options="-c default_transaction_read_only=on -c statement_timeout=30000",
    )
    cur = conn.cursor()

    targets = ["site", "jobs"] if args.worker == "both" else [args.worker]
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    for worker in targets:
        lines, outcomes = build_file(WORKERS[worker], cur, args.generate_missing)
        out_path = out_dir / f"secrets-{worker}.env"
        out_path.write_text("\n".join(lines) + "\n")
        os.chmod(out_path, 0o600)

        print(f"\n{worker}: wrote {out_path}", file=sys.stderr)
        for name, outcome in outcomes:
            print(f"  {name:<28} {outcome}", file=sys.stderr)

    conn.close()
    print(
        "\nNext step, per worker:\n"
        "  cd workers/<site|jobs> && wrangler deploy --secrets-file <out-dir>/secrets-<worker>.env\n"
        "Delete the generated file(s) once that succeeds -- they are plaintext secrets on disk.",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
